apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: trueconf
  namespace: trueconf
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 15.29.36
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:

    image:
      repository: docker.io/trueconf/trueconf-server
      pullPolicy: IfNotPresent
      tag: 5.5.2.10903@sha256:bf772f9b5d1cf15ef71b3c99c49127f3f2dd1c62b87b3c5563ee3568d16c7fa7

    ## Enable host networking for direct network access. True breaks K8s security.
    # hostNetwork: true
    TZ: America/Chicago 
    resources:
      requests:
        cpu: 10m      
    global:
      stopAll: false 
    credentials:
      s3:
        type: s3
        url: "${MINIO_S3URL}"
        bucket: "${MINIO_S3PREFIX}-trueconf"
        accessKey: "${MINIO_S3ID}"
        secretKey: "${MINIO_S3KEY}"
        encrKey: "${MINIO_S3KEY}"
    service:
      main:
        type: ClusterIP
        ports:
          main:
            enabled: true
            port: 443
            protocol: https
            targetPort: 443
          http:
            enabled: true
            port: 80
            protocol: http
            targetPort: 80
          trueconf:
            enabled: true
            port: 4307
            protocol: tcp
            targetPort: 4307
      webrtc:
        enabled: true
        type: LoadBalancer
        ports:
          webrtc:
            enabled: true
            port: 53000
            protocol: udp
            targetPort: 53000
    ingress:
      main:
        enabled: true
        ingressClassName: external
        hosts:
          - host: conf.${DOMAIN_1}
        integrations:
          certManager:
            enabled: true
            certificateIssuer: domain-0-le-prod  
    persistence:
      config:
        storageClass: ceph-filesystem
        size: 10Gi
        accessModes:
          - ReadWriteMany
        targetSelector:
          main:
            main:
              mountPath: /opt/trueconf/server/var/lib
    #     volsync:
    #       - name: b2
    #         type: restic
    #         credentials: s3
    #         dest:
    #           volumeSnapshotClassName: ceph-filesystem
    #           enabled: true
    #         src:
    #           volumeSnapshotClassName: ceph-filesystem
    #           enabled: true
    #           trigger:
    #             schedule: "30 14 * * *"
    # cnpg:
    #   main:
    #     # mode: recovery # Set to 'recovery' when recovery from S3, also change the revisions
    #     backups:
    #       enabled: true
    #       credentials: s3
    #       retentionPolicy: "14d"
    #       revision: "1"
    #     recovery:
    #       credentials: s3
    #       revision: ""  
    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                ADMIN_USER: "admin"
                ADMIN_PASSWORD: "testme"
       
         
