apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:eekUFT9inD68HaHLnE6cdeHQtvQe01OBG4NI3+p8Hy4pu6l4GvrXs/9jVkbEtPPmD7QEf9WqfCBTpnWiuCuoWDtvWe3+iLMQWraZV/Aqf0PalWSmCZ2Nu8G8fmiOlZB2XBYMHfL7K/xA3uVUYYuFGR+8biCA7yGhh6vogpGJhq63xmrbUteK81h2Db67tVFP3ueUXFVUAOb5RFK82dL3UvmBiT/MFt9N5sYyOpHHh5yB6BwgTf1Xpw5mpNzSeOkmh58StJ2WuzOhtuGAYtTo0SMwXEB136Pwpi6ZTwrZzFkEbb3PCJ0+bU2JONip5SdL2/976pYbPGlE7lvhCnpf4jsaJv041vROYPy8irxn/aQc2zYlV7E25psLDFGgVfMM,iv:M5WL5PX8FQh9fQg534wnxdbepDPGdumsZmN0FaeMm28=,tag:rx7cHsNBkjjVBPcExR+jpA==,type:str]
    identity.pub: ENC[AES256_GCM,data:PtKrs4A0YUmAU9MfG4BojbcZVd6DqH6bU20VsjvS9BUslNOB11y7MfxTQK8I/5B7DImmIiWTqdACGK5OZdaiwOm08IafmwhFo4H5HepUINbQtL3ackxO6sliVVeAQGmY5lTdFUI1zAH6cBKdf2XO/Bf5rD4UM8GpxVbEFtxjSsj1EZmO1FSUTLVq7TwVRJY70pwybXBiN5lBbZ5X+Sejr+EqkoYKdVzAUKHVGywTLAXAWZEFbSgJYaN6J0biRVUFm7mzuov4hfEs45x1jg==,iv:s4x3h7S/aYtAtOumGWTzgZkUOVSwMdqOeZ2Z1yGj3v0=,tag:RP4jp7jE9GW2jZGdjbkoog==,type:str]
    known_hosts: ENC[AES256_GCM,data:fq0PfxgP57toKVE4YmKbWQMyUCo2cSDvJ3M/UZauLkZ7TAQKHUWDcVTi4F4FnmKo8gZyVHAc+5Iuxgs7RX/blWnnDCW43kT7fAU3wiX/W00Fy3OdjDQYqDfpOY+kYAAfKMQwo8+XQH2T/SGnAGosyJLAeK/ikHV9Bzlw8T80QPFTEOaLZ9Y6FyKdSx2HlMTpJMoaLfjp9Ky102swotVpTUZfdVXkFxYuLJuw,iv:TllOg3sBEohGucdKsHyVDAER2gspU7rkZdFurjpd15c=,tag:BAznehcZYxOX/Cn/H71V7g==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1ahhpeqda220h75jh8fwfptlze88sggr70lu3vzzylhj9phtm730sj06q7m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvNGFGY3BQL0ttRTk1Zysz
            TnVPazI0Ym4xYVdSTjNSUi8xZXRFTHFXM0ZjCkhJMHc3TjlQbzFxaDhOZkNkd0l3
            TFp5VWRxaUVVQldxcVlOclFEWjN3N2cKLS0tIHlzMWpFTXk1SFlhSHRVb2F6QVVQ
            Tkxkb29HVSsvcEZvaUpFcVhSMGFxNFEK7F+NXvZS6YNBy/G4Xw92/b7Nr+3ShuYq
            hxxbocyPfA4vp/mtO5q6alFrY6FFTYplPtG6c8fRBGEQMk6VM8sucA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-17T20:39:11Z"
    mac: ENC[AES256_GCM,data:AXSHamn2PkPO5auLt7AjE7D00o6EIB0K2b9Q4lVPsCzsd975CMTkXBxh6qZsYqqe0WpKDnh7VdJo9fTmxpoQlED9OiE8l5K9RFEKQyWMUMDxhKNl/m4plo6K1kIvJJmtzCUA7HVcuz4nBh5/3WeRaRC8uprOd4QzZAgOjgMxhdQ=,iv:tXzakh8QO5j8KgfoWK10ZXmHPe9mnF6m9uP5GT2j9X4=,tag:QbgOzGXs4zwvi3UTe1sO/w==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
