apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:mIVMzEQPVgmL2/eOmMoe6CE1kI2EOJKg5ZLhdblsmu1pegepWi0IcHK5lXHEYjL3MeBEIvUDNCUtn2WtfDxImMMVZ9FN4il8NQQmmdBTsS6CUOkhFWIFoZ70iACv807jePVANdj8i+Xl9xSoBNbdlJs2xs2sA2sHina4g8SfQlp0ZrVd8pDRkaS87xvEvpaffDA2VdsiYKXyDvkeFQ1WQb7PwMu1kZzsl4sGTeGKenLN3oPiW5nFlzWWOPJkCmzL3nIm1MKsLHMalYzwgylV+wi8p6vCJh7gOsRRPYmhjRIJp+A0gHkofZr/9Y69RorvtDJAz7jpGzYzA0pTIe6CQgcw3C7znViFifp4RwnNE/LhSb6IA2nflKSgBEkqpAMD,iv:iCvbNgaYaxz65qIMfvesOEmA7ckUrEI9fLD88KIRY+Y=,tag:/plUYaulyDKqNT8FVeKr9A==,type:str]
    identity.pub: ENC[AES256_GCM,data:OVNVzTudcVgRGDZCrPQOlPfxh/eWEGGBbZoP+6jWtN0Q3bS2mRqQqtx7zV94YJiqcyFQs18m5GCXezf2JLIRMQnxWjTaEjJqTndNk9vb29HbGbHQnbdFeBXNS9EE8FkUOrnnR6XeAL5iFaubg1jBScCer4Me+eAOfsXxAGBkIkJmNsopbprTkivUAE4dtyR4GnicqRNUQXyz+rYULwKe/mUMYRubclS1GLYU5TN2KuuXKldEtSM0Kvt7IEfBBIO5+Gj9F3AOsDka4j2NdA==,iv:sZrZJ44A58EV+ReiqiEosqpfb/5SwyXAIsnRHoRCk7s=,tag:naIFu3FE5e4LWjM38fT5sw==,type:str]
    known_hosts: ENC[AES256_GCM,data:+naAcxhwWg+IqDXV5E52dgp9mXNvrR/JYcTsQNWamxCKROxUpGbuKXZwsp03tdk1UQAHXhAHB5avjC1MLW46oMD/K6Sf90zwJ7whoT8GAUr0AE5iukO1eJ54e3VCxwKAIj0Z1J4XFYSodXWLfZzKVr7VOVOws02HhJqKQtDWX/Y8gv2t7lWyqmE/S1TAW4/wpY51g17nURcczmEfqgGGVjIo1mocacGrBY8q,iv:UZmT8lWcPB8XfynA6p25Ved0FlcYNdqSzRPApn/vrxc=,tag:6ea8kRIB0HSOmEKhC03j7g==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1ahhpeqda220h75jh8fwfptlze88sggr70lu3vzzylhj9phtm730sj06q7m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRL2VkMlFKZFhUdGoyeDlS
            ajNOampITW9Yd1FsN3N3WlF6Zkxqczc5WG13Clg0ek90ckFPL3p6MzlOV09iTTMz
            V2dtaXBIalkxT0hXdmhPMjlMMnY4NmMKLS0tIFdiMm1hVUtBV3ZTVEQ4c2I3SUdu
            OTBVVTRnN2VjQSt6RmdUeWZyczM2SUEKOc1epaC3xNJ6QafH3z7ww1cr/DiO2aEl
            nrrUJYfi66rZHHf8ZxwH13P+a6Qa/HHl1m/IvZZ2dV3SEPfyh5YACA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-18T22:42:16Z"
    mac: ENC[AES256_GCM,data:E3FcJ6v27j7BzRMVpO4m6rzI3POv/7Cm84eFzHjSkzihk97i5xwa9Qn3w4Tn/kOlcSusRMaIxQZEJpJlSwHFUxEEL+4WmQaDZsggWCRrtyupVdESAhO5M7uQerjnMnGDzwMxK8PIg5VKj/YhVOSXifoDyBZbnlvv2mXeugUcgiI=,iv:foEQ5zVy0Ej9Up8MUf8cj3SfGOa6gRJxI7AzBMzUSwU=,tag:HBviBZSXzsMCi6sAs3l7nA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
