apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:s/a9xvCv+bxcRqGzXZZ4sIHgCmJ6YqzGfdCks+c2OtOTXmkQWmVqWK/mnDwmObAs0DwK29sO6FtZyq5M7J6ne/5zsA324wVFFUmRAArzIQ8AyrFQyAzbkCSivcSVoJGsRYzcfBtjne8ijzbCMCfphRngn6DAiutI57kw2pxo+8zgz/3Uwy0iO1VDgosZvX1qMocFLLnAwWrD5spug1yh0zs1kWxlDIAYPo0KCTPZ4IEM6vwPaZmUfrlFpwCriOhZmvb5bdcvXVurS4rNYnVQz0Q9IJuupE2piOn9otSK1QMF1Djz8qb5nQZhirY7XYGiELViqoBY0IQWeIJSCXNJ+Q+/2GvvMbv8I6gE9Jo6pHtcm8QJlSo4Hmz/1hiO/zdC,iv:s46j/jiMDARZSgGziugZWPYTdHBGka/cbfKTbaLyzAM=,tag:5PHglp4Uorf3oIPcI5DB0A==,type:str]
    identity.pub: ENC[AES256_GCM,data:I5xLX7g37LaFh6xYuIY9xRndfMd+K5u6kUhoTpp04r3gu6XIGNW0jKYnCLrbqJ8ELGeHV6E5b4cQ/JDjqnRX6fqAFjtuKAjIhimF3FXFIXx3GUOqp6GVZzrJ2hLUKfNejZ+GlReeb+UOabgj8qZqfyXfx+2xA1pMFR6Cn4xGgo0lYGkS/ol5g/Ti3+cYfRCsKeDwvBMcr7rc2hSQfozf4kaxUMc5KIYc+zHpfJcsHPF8Zx9H21LGzUw1n/+6/QYsqXT3lx3uSbQFOxdjKQ==,iv:qNFnICQ4S512URrGIY9OFzWwuqI2Ad5A8fbDgJw+JFw=,tag:X7gpwJf15dzmzF1F8QcHQA==,type:str]
    known_hosts: ENC[AES256_GCM,data:RqU/M10uMXGJGUJJ1NqSXx01d6Phs6bSq6eouUhG9F2x+Ocy+R6nM0gx6SqhaC4+itEUyJvSR2RSswNOvQGcpyAZo0uZNmH8aai/XA1A7O7wd1MuHmsr/vs6IOxl+OYYk/ka9DwHnig2h9IrsjWYVLU+gXCXEqukz1MQUlHlKJwXJ9wKV3N76Di39a6QwjiSImTPMZLG6UObWAXBZnecpBDlu+iWy+Oi/5bj,iv:9DK6C/RsWeiHEFvkO6REI5/iF9KTLoRCziZs1cSJLNE=,tag:PSZyflRazsl209+sDPDndw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1ahhpeqda220h75jh8fwfptlze88sggr70lu3vzzylhj9phtm730sj06q7m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLeEVYOGF3OWFyaCtCVTNj
            ZDNDOTdFdlROczQvb1lsYkxTSkpmNjRha2d3CkJvK1V4ZGs0KzFNdDhjOHpxV3k0
            ZXVicnZ0WlJmUitnVEg5eUczS1BEYVEKLS0tIG4zSEpBY1FxKzl3WjNTVUNzeW5R
            UitpbWhRSG9Rek52b1pOVmhheWxFdDAKPMV4go27hJ/xnHVIe8t7k77M0GOiMuyt
            VfxG9UkFadNRO7NQgMnwio9sDfRvvPtkZhG6el7tDjpHS1WNeRiIUQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-06T16:55:00Z"
    mac: ENC[AES256_GCM,data:0wFrPuHTI/doT3nbrEK1i5ncDxa5cT9fPR4f4+v76e9ir683nXP3MN9EXWk/RAwOrYu9F6f3VGvtXKp7lz83CbO29vpcIHu6V4vkiwCptQJkmH9skiLvK88k7FUbFncvFVvR8tltn3GF4pbp9wvsKcvZSQqUTk0/v3UPVfQ92u8=,iv:egMLrz6yanG7rBOCY+ldr2JkV1kG4hoXn53Vur39pa0=,tag:XzrNkhS5VTc/IgbVUXYgXQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
