apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:ZIZAuTuF+4JQQyGHQLo88jizPcqt4XH7fqUUCk7EEnKSiYs6TtkhMBu4B4ZlsgZ8nKu0db2+NS7zpRqe95hh7yyRwDfEi00aOnn4Kc+PJiUQ2QPcJ/LqOvH11mdDjh4jikqnTlhKibkHynzYAK0rgs7AdPBxzY9KwpNBcuMSOI66ZHTPQZRpEZnT7EetT6FYSTmScNpj2bHFAYjEX4m5ASMQVnn+zXRpc801KCvcgj65HkWewAwOBxVepDBPbEpRBft+wkKIQJINb7P3XPXkg/hPDsYGDKGjf1MBK3jVpuS6ka0HFwBOjlm56cefQkPL8qEBWsnoYN3P/iGVIRxqmP56dKNcFIU0pF56W3Bvx2xdQmHCUWfl/XcGrbdJpigN,iv:/lC5aKaVdTsjGtcIwfjoFpMkoj0RwpKXeNdoCrw/c2o=,tag:a4ARXLwDpEF09YqlxkIy2w==,type:str]
    identity.pub: ENC[AES256_GCM,data:f4I+S4vmcf2kY+nOcQijxLku3LVYfz0NoglB2l4BDTCLKhBqRYFsyZ7ZdUB/J5K8y5PEJWy6DjCD/8QjY87YFonIcWh+XBLWXKsB5pg3vdONYpoD1mDOHiff8L8zjsz8pPb3xMQujQpptjuLsaYzfv0qbyLPSAz5k8XaA/qk3b37zARHkDB6RwFgLQzV6noBpH47cc5GG8Zk+l7BOWXLnj+hW+7bk8CcIiY5nIwONtFNkEYSEcQNSl8eZBvEzo4RVdB8ThpnBszb1DK2QQ==,iv:7lwbsd0kBXW/Bi2RU8PpmxWObwrAs/Vipi3cjeT24a8=,tag:1soOIFgHSS6y5Jv4iRmcvg==,type:str]
    known_hosts: ENC[AES256_GCM,data:2mOhsNiIbYcb9VTC1wWHN+OBb8cphTNwlYRz8JMFi6T9z5auYjlxsyd93N6GEQaI65f75eO2zgd6aJXGsEGdBEcHNE6imo0BDBM4HWeEs9qvddfFcXdBXJHtWWQ6lhXvii+IdLZuNq43WvYsH+Dxyf7zygH692ZWlSCvir3L14RGqaza2ble11M13HDmTW33uH+k7gaLh216X490oh+pd0AMkeAci3QYYaP2,iv:DpJLIq6b1AMrI5mPIUaCaH6DytfURWlCtx62th33Lf4=,tag:0sLzJAaRNJWyBUc+MasnAg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1ahhpeqda220h75jh8fwfptlze88sggr70lu3vzzylhj9phtm730sj06q7m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBleWhYTmdPTThUU3pyQzFa
            c2RhUXBUNm1jaDlhVXJGOUh6YUxad081Nkd3CkdPb2FGOTVFc0RMWVBPWi91MVlH
            U3hWNTkvei85cEVPbVNVOHlRcnVQTDgKLS0tIDZSa1p5KzRQVGhEemhpTDBiTVdI
            NnVYd2s5Mk1sSkRSQmRwbVZBMzk4NTQKTq9Oo4yICv1vKnvOguQBxPq8Ag4lyVGX
            W8jxZd57e6MOL2wXro0rec0BkBZBXL68Xve3LKKbNdtuoDCGZaxfXw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-05T01:42:27Z"
    mac: ENC[AES256_GCM,data:gAgFehHxUlsDPKtfdlgn6TzGQfm4YGppOtHaxV2i4px9cENlqlVGxbslITBxHCokRultwW2N3GxLy44bZozphwpGCS+sFFO4gqKpcKJNf3yyEYM6RnCtLam5IWyG8HzfJz3+kfPQsW/4cKvs3Z4VE5YRfmYqedJXTpcakGBtZW4=,iv:cZasraiaCth30ahKdJeA7gIfXYes82yQHq1wgCD8nQs=,tag:jXuIRsDRTy4UgawOBj0Iiw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
