apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:vQkPRFn112Lr8ViSj9ObKUMxVUT2IoYYjxW+eleT76ZZMEHRmCadpFKXigTYGsItiYZuz1FdHJSOL2xRkn0JRjrTSa4oEvV3TpQf3wlRuKwGjVq6L94VFYojb2ndxxDEnwbKE4Fqh+iOD2boUQfUR4TdN9+QBW/ISV7sEHutTGS4hXcg26XTENKvk/Wg+O/EoYg1zSbjPJ5kEJb3NeBVEfAkMmpkrA/xTdK7nyhfBgFRxsi0VvGNGB6vVQswJbip4c31sZmwwk7Plr+IWmXnMEVXQj3yUO3ekusKTP+9kn/ov+6e55JvBHwXJhfjFKx07uH6/BZ6bsvBqv/KhfgIKQw+D2aGf9bExfjneb2eLAPsBy/mHsbO+zg7xXbUhm8U,iv:54LtHKmUQLEw/eKIZyRr3ADpQyfahYy2QXrsY0Yi2fE=,tag:KdVROs0wB79qwiKmDRII1Q==,type:str]
    identity.pub: ENC[AES256_GCM,data:riqlikHA2lHTChCI+Xwp6PRqLQ1FjiGqfPcqsK+mXHIcizLC0aaY9jTTJ5/4ueyXqopaQ79rXIKYs2qx4789eZqMfEbgYnVVfppB4zPRxqVSvEtoTN/+GbXr1feMoDECU+Hc9AGH/7cxuzrtZwgCTKw/5rc1nQsUHIMS0BIVFPyZVNM/ELzvlzDkwFkBImEnBzhJSNaEIkBQm5F325M8JBsMpR0EPHRfUJqsBRLht7RbxrqNrJhRQVqlEBfOA0ObKUNSi9o1JnzdRjf8jQ==,iv:BDdOJ7tvMgyUO7dMNewB36U6l/jnNtDyaDT7ScKblIw=,tag:RwVqEh/LOF1mYk4CmEGPzQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:7xWNO8fUv2Xt5r9BqDw6rK8rT1dCRvTOWEOOWe3kQOCMKnQnUZ2vvZNIQLgQQWyYWKqvycxDmod7L3hDnRq7GqNxPb6W8/C2KMF7zGK7FLPfWfTK6p57KwCiE0VPqcubsk8c65jymV4yCOvFBAiBcCcMUSWjUIqPx2+/7SZK8Q6ihBu5UjCw85KuSKEdTo7ZbvCKpPomRQpLO8J5UKQMHHPIBgNVu39kXtIq,iv:dlXg/936W1rQTSoBHt9Bam2PRLwasEBFQB1uctfNlt0=,tag:6kvdWN/2EbxQdhoD1G/JuQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1ahhpeqda220h75jh8fwfptlze88sggr70lu3vzzylhj9phtm730sj06q7m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhKzJjUlV4QXJjZjVqTmxu
            OWJwNnc2NFRJSzJ3SFR1b2ZtZ1ArZnM3SEM0CjNRcWZyQ3Y3NU5RMjZtV1J6QzRS
            OGZrMzR1UjcrV1lybmlseFAreDBjSWMKLS0tIEVwbEV3UjRuZk15eHVPdkVhRzdL
            eDdXc1d5VGtyK0VjU0o3a3p2UXJDcVEKBdAoGfu5BP4cQNWffPOIaGMhxmzhiQW/
            1RC1BhaslvcZ2lJp+GhcU2jwI0dfh8PdRSD5jnjW1eZbQIwJn+lybQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-19T15:20:36Z"
    mac: ENC[AES256_GCM,data:xxbSmicwnnjdnaApUSMm3LwlBmfYlt8CvSJM6uHMEETOYIhAznsTDzCTSvvqc7u9n+R5oPgbnnFXGxazE9uWmuiizFi6nzAVjOQ39z8ZsL/57WG2N1NNm1QyKWuaiwrrxi0WlWnRYDl+xRwq0ghMILuTGUpBS5I4z7hYjUmdYiQ=,iv:CcMCwCCImNuJ5k/hAEASG7ohrUxxOukmQAbIsm1Jzv4=,tag:9FYsU4Z9HSjUhOwetuG/3w==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
