apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:P3yk+ESG38PY0DttngmEzMM8KD+nK6tZF0x6byV4wrnsMv/8MmE3dsj0zk1TX37COkk5XKc5JQjCDxWrWfauqMMbOQpGh+cZhBj6Er90acEnO27GxAOxFZy1sVptbPVH8366uqXVLzMopBw2DXTZsPuvQ1Eg15CLJe0VkxwHhxdGX8asBTwBj65/RAyuBjdCipl4CiTHoOirYAMY3Yq5eSwHd8NNfLdkcHaVb3IDy/C/h1W3XDWv3Cj6dW3ucRfVgMxBqwmQKYfdi5duRUjXfyDEjtmGKNiak4JoXiSTOqsxu0Vl0hL8AP8GtaSl+ZsDPccqxKc8xVx+Qw/wAsf4oSNEcwHDpb4uGkYT9TUYyhKs1J5nIhisCDi1EAY7Sh9A,iv:laJtZfuAOm2VU/uP8V7rm70hclNaKnTA3zJvkD9SFoY=,tag:IG4pkG2zokpTZhSt0oCADg==,type:str]
    identity.pub: ENC[AES256_GCM,data:BjwZD1VZXS55WbLAu154yV6N3NcFJE+CcbbbWy4AH7DvT6QxQQTReOOcNpycQ4mUjXlQu4PUunasuL6rxz/QBIb6ZNQD76vfwPFyr/pvqHMUBY6e8Xc2xBuwGgeDUDBzl4B/n6HMXiqj7x2drGrwZi5kyeuZiIPeoOTtznlkPSTNvbuHt/kMlH+14kTxhqyB7i5q4rwpDKcHfs34WlK9sRKeb8uoOxWY1ZmB0Kd0ZEfvXLxUpIgfqWG7PN2H2wdsBxdMJg0syKP83/o9Hw==,iv:6eVzPO86DdeFRn0lQfYT48Ot02fr5ibkHzyK4uuN29U=,tag:rMX44sbJdQO0ZvTaU170jg==,type:str]
    known_hosts: ENC[AES256_GCM,data:1it1ORQK15P7pOKpa52TOtiXjDRLgAFMoGcYiddOATH44rfvQjcVEcjhQ7kAgHq1X1OhqLE3b+qNv5dMcjhMofRPOSSN39/+/S+dt37rj4beaitXeSIGKT2+myfwlUr4uguoij3rl7kEut0wVqguwk36NVB8K93MUHCRoUrlYW/fdYReiw1tbbEyitwWaa5qn0aPpBoivSGxJ+B4GlcLoOv+D1QFyKtkYUej,iv:MN5Sd1o1E5kgIB9JV//iSO9JWKBziFlTpKtIqCmeG+Y=,tag:Dv8CH3tpVp1ilD4P0jDXqA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1ahhpeqda220h75jh8fwfptlze88sggr70lu3vzzylhj9phtm730sj06q7m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxY253S1MzRjZwTEdDdU9T
            R0drUGNoeFdrbFNXVEZJZW1mQ0RXMjd1elVVCnhoRjJrSFdmaDJEUHZ5L3Z3M2M0
            NzhJWnFYODBIUUpobEJnOXphd0h1VDQKLS0tIDVSZ1h3bmVvWVVMSVhtbG9RdVNp
            TFAzYmtPK3F5dGpWUTVZRnE0TkFRM2MK0W0rIPPqZToLhAD6hHXjMVTOh7LIMCzm
            od1yaCAhhBwIZi3o271ufnvKRSfePfr6G7mDzWuvHLbntXuShr7Sgg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-21T23:26:35Z"
    mac: ENC[AES256_GCM,data:CR9jzo1QdkYiqR6K3Klx1eZKfXr1kVlbU0OdAawGIHuZsNcbBYlX5F4QtZo9qPydotJe7q3nXXftc0pi1Ws3WsDdVtck6TVRwdYvOLTaeSoiDSUmo5oTYGfmoF/kjZUDdHBLBLojgNvC/WNC3m1AnGiZOGmVRKi43U18aC5t8M0=,iv:4+spJGFt0DXfke0OFzOan2jeuIwCPISTbjTOdxZ8SSg=,tag:4pXOgG/ZaseUUwBSwUcrRg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
