apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:peXcEqCgEkFi9BDcCVSL774pmSsOT+4Dr8cSDcTNbTmyKQjfqXmLoVEBDZwVeR/aYmU22kf4okzxSW3mfFKugsXjOmm+qnsLe8PnRmxoY1/4NtWDZTi57qmkYY0UAfKzR0JncwjG99RDWJsXDNx/hcVIJvE3zvO4t+JYya9mKodkRgYcDnHfCIZEcrS3moFSW7vQ6LQlQs2eOXuMTtlYUdBLmHcHWe9ecE9YIH8TiSfKVoSLEoDnMoConeAGJNY6I5i7HXjNMkgXeevHdwXZFc5CKYNb9/knbgWBDvQoV8f3P8pquaeC9jZEEft/AAwVDW+aD5Tr6oMRWvJszyof8kTwsyVW0UV/aDlfm5Vu+tn7gMTM9AfsW1LRdquPV8iH,iv:0xvBuk2SFSoys/2dnb3GulsZyiZu9y1xy2Y1AAzKZQM=,tag:UcVZYOaqhHfySnXRtyNPsQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:55bmMPlK9k0pLpeEE6giENs77GxaRvh3cHIhFfnkcWxwVT7ehUUsPBRg4RMXkSJALB7KpQwWybuZsvGOoUQGLA9aNMsrCwftTrffnGRDXG2LjCfPUd1G8POMLA040brJeidEXrrVKK/1J2Aj79Gc4GtFtdB8qvkR9gya6VHUJArLbpoxuuLW42kx14OCBcj8bhuyzQWXO1tibHZ9Bzx09xtjgxxYx0FqGRaJ3zaYG7U88+dea/waJ4H81GBFeCq2P23w7lNKPy3uCKev1w==,iv:yGev/HY81JxjoucfHg134jRqoJrkxj2gvZxCF/7vbLA=,tag:vJQi8XOfFRT2D+1ygw0rnA==,type:str]
    known_hosts: ENC[AES256_GCM,data:qLz4oopEbZhrZX4PpVjdt6ZFKnrLxYtscNthTAa35ZRiJOWAIrCJlTB5k9pEjSLLOaK1oFZl1HefRezoBLD+pE+t8P442g6vgRU154IqcyiJnRzdh/QI17veFVCDuLeyJMo+kxgdq/Ea62rCaPHH0AD1eZTAnUuin+vwb62jiJuItbz1BNmYNYTpditSFUbfOSPXnsBAZDff2qrEgRRvfTQvD2S9t+nWEmue,iv:dS0ht20XBjV8am3cg39D8oBTK6/w2uY62irWB4eiPLc=,tag:W9GL9WyiZ37H7rKkvtCLzA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1ahhpeqda220h75jh8fwfptlze88sggr70lu3vzzylhj9phtm730sj06q7m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4YkpjYjFHci9hUUVyS3Nx
            QmVFYnZkOUw5c3BKUkpLTFE0ejJJNjlnNUJ3CjRDQ3lNREVBMjV4ckNESjhHWnFT
            aWd2RVlWdVk1Zm5oQXZpMmNEY0tySmsKLS0tIGFwV3RObEhTTXNPZ3lYODZpU01R
            KytrNEZsMTFqMWxoTnhrdnZDMCt5aFkKXiA0XjHnK8fsnLN27LQ476YdW1J6YKHs
            KW582e9l7KMxb0aNp/Doyy8+VQDa2lUuvtwjjaSc9liqrwgc9200fA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-28T16:02:27Z"
    mac: ENC[AES256_GCM,data:iYkvRqqEMXEdzm46tp0mHKSkrc6Pe7+iXDjPzrbkE/RudPi3UTGQp3EL95JmKf7A4aHS9kPr1RDCHalV6MQdgRyTjsTpA3pAcQQeBKMq/1Fym6tasGN+Kz/p/FRhJFFw16LVuLB9fARZcIO+zzEvfbpfUzkEFyaMrJZ2D0fzFk4=,iv:pc4TwOZIA4lrNvpu9sky2ZcfLjWV952YFaUs2jq2+Os=,tag:gTNrM0i0qa+MuInuUkMdwQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
