apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:V2dUBH5agnMGYFU+TN+qGJiEf4hkgyPcKjAmB9Y51xGpSX9Inq+PBPcrPryRGrZNgGulRxHRmr6RpYbtPwFZU+AFioWjQbj8po85PLFWMvwcTRMZnIyCgnhfev6spa4NM9MWnYWiBC+K40pBfiZYgBMijEcgJ2UeG7wNiro3bBssGO+j2k89khtn4sd2ylXZq2QV0KkSHJnUuR+WeNfE3zVjf3CBe9h41WBctYnkyvVhs/tNmNS5KQQ0SY+P2LS2vocNHeIHU5VlPnIWDAAyIW2zxorOQQy8yzbvkEPjC8cAtiEJaDsN99N041OXdNEY9OFIPJ5jkGyIkRVRQVxEk0t60MLCk2zEF7SpDxl1+nDfXSESt6PKQ18q0Cgvsad8,iv:GxjgXQcCcKBC5AZM2suC8Dv9682HbMe32h+ZSJkQ5rg=,tag:UjdLPF8P9Vft/mvOcptRjw==,type:str]
    identity.pub: ENC[AES256_GCM,data:vVtVVgCCHImDwZ5RygoPCcSNXRzmFBinoDP37SHosMA4qoBRAmcDr33zzHOIT8DFk7gVm0/1CfgnITWzwFKsHp8whUbaNFSzylG9b8Zf27dtg7/0PnWC/fJ3rLQrgI1ZwKXq2cxqjNGupzCrqXqOh8S5r7GggvSwEjNptae6Q2Z1vUTC8I2i6qYhez+kUMWci1+/7Ea7eQTfrF72B3rQSUq4vAU9yTNFx2w+YMuhtwLaDFt7XB97hR4g6u5n0ebsv8pEblx3wf2LXucHVQ==,iv:v9/16VU/3A+bnpNdXBE3LXkSMASZ75TmfqovYSR2vvQ=,tag:rRwZ9Yxdqdro47blnwcjvw==,type:str]
    known_hosts: ENC[AES256_GCM,data:G0D+pFLbr87K+zJs+5AzsHZHg9HLpakYI66FFGP7ZRYhrToRuMryUKuOo86De7Aw3vcrHGYcqKfSKUHFfQq4nBXmunZ/EOVZZoocNtjXKu0owlwVGfiQRFtA2s3OmbqGeMZd/SO60OimSGsRIxYYjltuVMPu5K26xjKh+GhKggLLHqdbjAF+LUGBtRyKtUvGkjke4DSHbhgqud6uqop/ptlbaHQmpybilXK2,iv:kp+JbsCI03kD34YGqzB1fByDBTcVLdP3s0wRV5fSh5o=,tag:BTRQyj6Sk8vErGafv444Bw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1ahhpeqda220h75jh8fwfptlze88sggr70lu3vzzylhj9phtm730sj06q7m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnbGdtNWdtSk41bnc5ZTVk
            UVpNRmxGREhkdnJIcFBFN2RZNjlxOGg5NlQwCmdzdE5lK2lKeFpCNUN6YUdJMm5X
            TWN0MjQvYmVLYkNFZ3JkNmFIeEdxNEUKLS0tIFJGRUdBVk1RSXR4Z1duOHpyQkND
            akJqQUtUMDFxM1lDd1Ayem9VSnZsTVkKu4lCAsZwfG+9a8sH04fxYenYkqPEZPM+
            WsyU+7Y8suCgog+gNaHJY8OIiH5+P6f8EiQeJ66KX5z5W63Tiuh+xw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-24T18:14:51Z"
    mac: ENC[AES256_GCM,data:DRCTpG3bCEpsjL97gZpVlwPih7MsiTFxOds2S1w+qynaFN11MbkWDYVEFW7baLx5C+bpGBFzJw56Thd+UaTv8fNu6dfA8sxV6e9Z2wVv6yXi+wbpnqlLKtlUdOL6Ktjii4KHyZAm9+0+NYTfVvJBBn7YB5aacr9+O2HZJq0COqM=,iv:cyl4sjbS8dakbYusjXIWbu4GnK8nNSBvXkiUAthsgHI=,tag:hQabCGGKshz1WYZT8PxbEQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
