apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:qV6H5xiUyIVJMcZS9HLE5rV2vNUtXHuUpyls/SrlXLJ1C6S4d25FsrhwejDEDSXvBbjfLutpt+7orsiL54y6wB0FpwK+N0sgO30UKjorfB38z2Aq/Ekaw6BY8XOze9MzRV4CDOlhri820auo7HHNzkAj/r/OHx+vGs6kTVEuEUEYr8Vd+OiVnEgI6rmAYXMRTxO0p2OaIyPI5hrmx5nuPIQJFmUrUuDGG6Ry0rFIBClJPQA74YUveW5FVwcR1+Ztgcs4fYURTxgJhO4T1/1uEXZdPFQB8u1//Q712EjPWvWFf3qPVZk0wYhEVOPGoruMj4uKEmsum7Z7LCDPiENUOm32stkQWOH1PyFeB5eU3NtEbcMOug+YudTKoXbC+fDg,iv:+gxJPhVhuLbTPdpdtkNhdpsribfDTq9shYIGzkflDS4=,tag:cdsT0ephZXdmpxQccC5zgg==,type:str]
    identity.pub: ENC[AES256_GCM,data:4Rc1hXCuvrVcxPvCmBsmQJkBXqkJcQQNmMJhZWxsCD+jBNDtDdB88mOo4XsP6BxSdTExt46FQnuQ69inZ2WOZsv0x2v47tXGscHeFblSCnUclkeNLVxGcJlDQF5/xw28bB27nF6Lsnacn/+cFtqhMRoMVlTG2s5PoETOYUuZo3O5z/o0Xjlz72SkdNpTSxSIxKkkYFVbWAcSvFeWOkncf73e+yEIpyXHqMSQbMBMn9k9NxP21Ae6HSXrgoHbursNfwOU3NnizstxiAPZMg==,iv:eZv2H6eL+fbdURwVR6B7Q0RHwQkvSdDM58qazEBHuIo=,tag:goa+ElpzdE9/t3i8JOmTfg==,type:str]
    known_hosts: ENC[AES256_GCM,data:TowRkbh0jAIFxoIk6HBuAM0BPuANbmBaqHmWH5gxcwKhomE5FUwwPCA75rIXkMg1ZG1PQiSLE407/b6rg84oASKmyaKjE1JfWwhIgnQIReSBEbaHfqwUkGNOsc33J05vzBmG63O8t5T7l6WEC7iJ3ZP5gXPaiqPmKTZsWyfLH1TIegEJyLFbQAyM131aWJ69QjQ2hMDIZB7K6rECUD5BsRE382O4MGHdkIGY,iv:VVImrfW+WoB9AnyKsRKRnkZ8aewh5bVNT9PoG2HXtXM=,tag:jkKA+xSXSv/eW1DbaIixYQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1ahhpeqda220h75jh8fwfptlze88sggr70lu3vzzylhj9phtm730sj06q7m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1cjJEb0tqSWh6ZEZKV2FE
            Z3ZySk44R1M2aUtWeWtNUmxiS0hkenJBWUhnCkJLU3E1S2NkUERQdy9kZXN0Y0cy
            Z2g2TTZ1Ulc3SVlyUnpGaEFhNWg2UUUKLS0tIFc5WTgwR3FmOVkyZHZpb0Z3enYx
            QjdFMk90RHd0TmdlQXZhdEkvZTJVaHcKi6hqnMX28q4II1POIbOxhSUbN8aUQd1X
            1NsaIImNJfLzEKhAf6rXk/MHWgOdF+dczUi5gBDkpetmEdhssdm7pw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-30T02:21:39Z"
    mac: ENC[AES256_GCM,data:7XhXnTJwHBDLs0wrnOMc0Xan5XdpophtCauDXjfaBFBHXv7PbRqjoDCtF3bAad3uBFP0D5evOT/JxPYEFdggCHkGNOg4hGVfA0UJOVjVmqqu9sRN2zwlYkFpGicx+f1tjky3wgN0MBCwJmwg9q1CRjXDEeDnKQbg7IeUlx4X6TU=,iv:avZHlmijqqA9il3NrhkKMtbNdC6IZy4sFJXo7hq8YwY=,tag:tVX6Q9WcvYvH7VPoaPVdtA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
