apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:1hQdxzri67L8a2hNYUAYdh0bfvvSSOsNgQPojUav61JBnEo21aZd9ysXCVz+bGCvJxl6eBW25MjNrynB7fDNhcEbnG0FblBBFymr4+lieRChRAFu9WKv/3CQ76W8OIZM4+yfj1x+MaN0LEIQa5ZmF4EJwTQByOBCUU/hzdkfca7QFiGyed5Nx3sxWYjx97tdHvYNkSM8AVcP8Xk/l1rcVx4XiwPMNM5lZ1aiWZHUXPJ/5+gPSFCuWUL5KX1fMKcZOh0C7kO4Jo4Lnv5nvORZ2IghIS6aR8aTS7tooMGRy3Dx/Sm6I9gTDrZYAzGjNR4V42YUyFhcEXg2x5A1bU5ql/TgpdFtgeB3OiQn4Rx0DHTuyV5eQh1x6Q/OR66/4CNK,iv:iysqNiLX/Jc1YkYIcPghzRLDO+x8mRDd087PaCcfalU=,tag:X2iAhrFp506Af5FE26wk7g==,type:str]
    identity.pub: ENC[AES256_GCM,data:41xZI+4N3nMn8naf0JeIc8Gb1tC3QzCA1/cp2r9gSo9H0gWinxNNrLC17twnNJW2YTU38SDApyc8asI+EHYfKf9RuQGL9J8o4NJ+Z7NPXYozcySmUOH1q+tdc2rKfTPGd9t4jcf4+CZ2PCE82TskayVhIjE3gAunuJRdTKEuEajWIKL28vrASjqx51WNWAzfrGZJBPwPLEygadzdgTELlYoJIwfNOlf/SFr2806nHF5EX3ja0ZhKKM6y6oWn6T7a9RnE1P4wYQsW7HHbUg==,iv:LVjbCIaSvwHs3DPS0WCdgUJtQNr+MlfEeVQpl0n+jcg=,tag:cg8fBclv438YRFLQocSRqw==,type:str]
    known_hosts: ENC[AES256_GCM,data:Q2pptxAeEJMLhAkUfFfszCoM/qKrDHgdpm/m1ooos/qtTtKyZRZdmpGUZ2wt3utL1JH/vR8DikmyK/vQH9h1GqHpTgijl+g7M/+y6lsmqx2VDyvZ1/IKd9jSaPdurvLNFJ8S/xTmEHCsHeKHdD/NnPECk33QYpOTfGsq5MpFVTqg484y19MtRyAi+0pEgvIToKElEUUIF6sU5m3lRdy3tPu/dPV230j+3ZEV,iv:iLxqyHAGDd9972tGY4ZVChdQJid8XV++hyVyogyvU6g=,tag:VRLkBvGndEbAG4v9pe3OlQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1ahhpeqda220h75jh8fwfptlze88sggr70lu3vzzylhj9phtm730sj06q7m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUWkduTkZkMVh3VTkxd3ZX
            a2hCa2RXK29URVF3S3NlY0tPZmVVRGpIODAwCjR1VEhZZHRKVXZvNGY0VGJPOWt2
            UzFBNUV0bC8vU0o0K0lJR1FBblV0emsKLS0tIDFRcGRwSGhPeXo4M3ljelhyN3dp
            aHFneGZrbitFVFVpRkh3NUlxbEFuN0UKc2L+v6gbkSZYopsu1YY8actWB8C8Yngm
            dM1HAUOfiE3mUIfS3jamKDLYSDJM59uzvpE9Goir75XiZxe8OtuBkg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T23:33:04Z"
    mac: ENC[AES256_GCM,data:j4ED5i+YmTh/ovHhLnz5Y0KFv8WBb3mIp2/OvdC/OaNmL+GRDJbl4LUJ2l9Cg5t7agekVP0bV9wuhVXycoUUQv7iABytFu6fHLWiDlKB3rXEK9as1mYx3Nz582IgZXZbTiW/gV5alQyMzsvQ+Qs1+5ZpmTx8z6CGvTmcwD+u0a4=,iv:dK92gqup4LGFFVLzRhucO8DgaoJuGaQhMSkNFH1ggYs=,tag:19ed6H5xaMjicWc9D5jmhA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
