apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:nXETjpAjuNKa13ILR723cw/pr0Y7w0uarrvVEzK7wf1NyVODcTl+WuzwpWCUw22mv805jRYpy0ifsAg34NC0qxLFS9xOPESXLX4qRnly1Z2BaynHzsT2AD7ORoqyKxQI7+T3YPh4ffgvuKVet/87QgAc6wfYTb8wPKMwFblAdnytLMZ5LWmrpO4acPMCu8oTShTsqJjvfwc8725k04mM9WUQ14/01eS7i+HR59yTupzoB3X9G+n14kSxkg5WwYPtwTSwS0yZovlD9CiE6i4SLN1OTMQ8u/+aok31D0cpbtpkqJLbYb+a5bRbA6O1Y3qKrfw1V1cra+5t3At1dI4VEqSmOau9D3BPwQGff0ix1qFqZhh1CbM9yUINMjR2HQHO,iv:buWsQD2zJIa9Sa9jb2aULE0vG37ANZt71LibCYrpxWw=,tag:10r68aOh6JJM6L5rONxAfQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:dmujrAidHFwnFZ8q3X1RmSbWznf1AdKGvY5/k2COt0jlE95iK8zVO3XaLMVd2q60oFSjoYjzrmuU97Eq6YZh/le2ShyfQnXCIef8EKgUkjRatKViP6W8HC4ddWHGK0Vd2QU6MoaePeTmVbWk5kI7O5eFrRFGnf2d6VgGGNevFxNgwli9fOUQc/oLDRmMy7vlOP5HYxWDsFqLnT0/ASaDcsGjeTjdED8psQFhVjQOTMXYxsFBn3HOND5AqsltoXiZJLmZxW3rKFaH1qQTbg==,iv:ledQz5UFyHEUhVgRON7s7dQO+ZLObodKV2wQz7LsWE8=,tag:DIRpYvhnMfL3bY61kra9UA==,type:str]
    known_hosts: ENC[AES256_GCM,data:IMyDHhxjfa7Ji5gLvF4V3tPjgHoyHfN0GwloTIzHnWORgk0sOrsA/CBHPRx7YdOKoo45g/PhBMBdJNe0SLDdcO/+yaq0r44h5JcqJtYSx7XMHeUdMWp8qd3T5Aw/U3mfHP9/wG0s2Y3pyIHdWuH69hFsPDgKcxN6ESdKTw0XR4a9h26+ZTywOjvFQ/TZrxQN0R6qci1Ncaat77JnMWilUIgHWAuazCZRDBtx,iv:mamU6/OF+MeGq2hrYqyExgTgZVtCuWOKxE5cIVaWtrQ=,tag:Jk2XIR9tdlEi8hbANVoNoA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1ahhpeqda220h75jh8fwfptlze88sggr70lu3vzzylhj9phtm730sj06q7m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1Nm1TM1E0K3M1RCtUcTBB
            U2lQczdmNmFmL1JjZndNMTRMQXdESDR1d2hrCm1iUXNFYm12cmV3dytaY2RGOEp3
            WTZyL3k3YkVKTGNDLyt4N1FSdklBVTgKLS0tIHc3ODQ1TTUzSWs3YWM2UExDRmkx
            T25tU0VpNHhSSmpjK3czOGhWR0hPWGMKst/ckWHH+douVnF/P7hJoJVvt06z6pwa
            11AY2k1jvR02OVJALwM0irjk2DQlHNWxJn0Scz6DrXK4oBfzNiCYTg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-27T01:49:31Z"
    mac: ENC[AES256_GCM,data:da50KRhDfRlq3Rfc9xFFRellVkzePP+9e4Rqc6UBruIgLuL67g2qtm5wKWEL2wFfmJVYXr/HOd2GxRHQ6n8gg7IMPWm1BQmMwHCWgqjAoIpEtaE8p3v3vHNw7Cj4iqvMC42OlOkqVfDgjnGY3gNvxu2QkyBO6SUzVpUTYSPqA+s=,iv:6VoWCwK2gbgb7kihxjyE4fDwHlSZ4LYnrz6hLbudmZo=,tag:tDs/mftEskdinGZK1VwcTg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
