apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:bK3fetxT+cO72npj+4aSWu2S+fog+nPli6Kqa3LU1lq5U5RTyffOeOdlI17ZGSFGZDzAF0xAAQoToc5z1jZoEa3QodiQQYfGDWqCaOeBK/xp/KausT3IpOxzULDTy2cD/0pZDHl8yu7mHWxCjPIHJjK0HIL8HSk4UKldDR9JeHoV/Uc6Io+ohvOrF3OqGt/Oo0vRtRGp1mWiCgu/tlLgpvgWVfwLLrwhJn7Eyhe2YGJPtmCuh35eUCgWXjLRNoB+6E2H76TZNLcZYBZUMhEuWgnYpVuEOgglgkSUz5a2SyEqmZlcsh7cUdTsDXpdbR99E/liJ/OW2fhFO/yysSpbmWT+OX7KRtZCCHqq0PoK+5jzM0jpURiBcPkAtyOKKGDK,iv:B+JzmqiKJmlziYCKoIUz2exz0FPkiJdSxmSq2Ymn7TU=,tag:6bCTfV02U3AU5gzUWj3puA==,type:str]
    identity.pub: ENC[AES256_GCM,data:HtSaoF/SxQV8uAZ6loERCnFVn875P4ZuIbeSTnwXJy4/2wG+vj2ccg7KPtrhCQJQU9Xn6hyKYefbjTuaGSZbYL/bLidvaLFmqOUZVbv9IY6pliMBhl4cWgqSXB3rKO9igI1alcCTAD4Us49KkOweaO0NyXvVeKaWZdpgwI8V1dwYq0JZEnMBA5CFzxv/foq3xQZ/Lj5WhI8gUlQiFRl5tkKpdpWf5ymZGeDgaCad3G9N8KiogNPkxKTSqu1ki9mNZpZE22nyzh055nAUuQ==,iv:wM5gKjObDQxesD6tP0B2CLUQxd/IeeD3ZpzIpKRvf6g=,tag:zlEBk8B9o+aMYsXpj5v+0w==,type:str]
    known_hosts: ENC[AES256_GCM,data:xIYZEQdrTdfxiOHVchRdGa6k1r60KQP15DlmezWcz+ktVz6JvsfISYdr+aRRK0zaJBBjLyFKp6j8XWeqVjDTqN/mziEDMxx22ie3NcKU+hAufCHZsoxkq0uhctDoIpXC5JfttXMQeXjrAOxPDUyJb10gcOFXyxHdVM4I80zDGsGBdcSYSn/TbBvKDUWpOHTK9iwp8eyeb+im9GrIQ/1XHv00SJmlLtzvaxMa,iv:fv2gvo3w2Sa4v/VTHSKBYol1XIuchegAlC0T/7H/h/k=,tag:4+ntqSTaDD8RbqQdLUDSwg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1ahhpeqda220h75jh8fwfptlze88sggr70lu3vzzylhj9phtm730sj06q7m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFTFU5cVBLcllVY1U5bFRK
            VXJSNkFqQjhaK3FyaWNYMlJ1OWhDOVRSdERJClV5QUtjVHk4d29RbFpVdXc1OENy
            ZTNPdEdXcHd4WWpTOWJjcW5CK004dmsKLS0tIHRYLzIrYjUraldpL1c5eXhOUDk5
            eTBiM05RMERDV0NiM05Kd2xPbTlrb1kKCO7yR4SvvXftzW4I/QLHcHyMaHS+tm4B
            qNEg/m/JxpvfDz4nmc3qu42eqOpx8KfMY1EgS2J13LBPvcidgqmfsQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-24T17:55:45Z"
    mac: ENC[AES256_GCM,data:x8p+ws4dT8O8FmPd7tymEV6R9FnK2oYa/t9B3tGLSmaBQj0dvHAdr22eAk73XkyVkvEg2xFxav7nJztYdvVdK1sjOCdW2GOWbbkPTMNNHQkl2skMZoVGW0tk7ofaBRn8uooAO4haCkNPivJN8YR+HkXpZKZfIcif+lYxZ62mYXM=,iv:3a3jj7G1adOKsqhzojtC5dY13eY5L70SWJnob+oB7fk=,tag:SMVLtQecd+l2i82U48J1WQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
