apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:U+us/ZoCyRyc3vzZ0lLmLUXD+a52xaX6B7+/gVOe/xRJkrfrCzq96vF6AvcsQ2S1aR1W2RQsDij4JHbNE2oQecIpc1ZJhc3XVmxccg3+Ql5lFR2DR9+iZjC3QFtPsOm2VmTKcFd+4h59l4vkXSVK+dJKgKKgqW3ghMMMvB0VQC42cyP0RIa4dSDmMNbTzt24jdrzHrppXFPYjNY5fpEs2fp2WGG6HpMQCcvRyjaXlfESpZ7bb78G/9VBl6v6DTbAzBnhSZTwslFx6OJIWFg/UsvyDBNt+nl7e3qyFXQWgRHj0fiDRmZm7eH6Fqk+D1VSZNwxQEQpSXeT/Bic4kjhpYaBXVCqe627C7p0byv5PbiNg98VYRYnyCLtiSpHbnPT,iv:8qvS6QYwXWkcujE0ZSvK+RRsoh/GDJIFutKLBSiK4Jc=,tag:rPrQstmBnZ/yZJimVCcuhQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:CHs6khFb8O/yhFk8P30WJVgc82pX700cRYapb8doOAkvvqyRh8Tuf2k26DwybBK4j4t3kaBpLdD3jU3WnFEVsI7KW4UDQjZiGBGCvy6uvce17em/5hLgwhoZyJiGCGdfneW6xjAuPXj9ycZ/0qgGLiNMR0SdrlOE82kJdC2f+xdfAG94HHergONCMRK5pIRRRo0r/fsuQT0EmMxFn9l3USmfws24jj8aWVdBnGdo10mzSu3hTB1eMgdJh5IrXDw+GeBQpxDMICA0rnydfw==,iv:ezZ+LqkW8w9U1/n1PAArvbSWAe12TjCiYW7nY7yRVy4=,tag:HIr5z8q2VHfQxPu5YAJA5Q==,type:str]
    known_hosts: ENC[AES256_GCM,data:NW9XxssZ/rDXaI7YLZQZFA81gtwx4XFnKh95Rw6/64l8ioAFcwChhsLA9jivFpRbLgCAojDG0bdrsxCvWU3mxJXeD4CvBE5DVk+IyW0oTzbkxxwpwcQnxkTR960DGBApivxO1f54VPFepbwjOlWiZeCW7MZPbd006Rz+YtX48CaXMLt6PtFoAWXhYcPaSN6GhI7I09SspwBS16j6kyhGaCO/cUeIWixPgyE7,iv:b7VnUOsUa/if7hUpH0iS7Ncbkzq5S4u87dozJOL/Zz0=,tag:daquJBAQw162KmoxNui0Hg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1ahhpeqda220h75jh8fwfptlze88sggr70lu3vzzylhj9phtm730sj06q7m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGNmh0eTFpc1JoT3Uvd01a
            Umd2TCtyVEZKYVlrbXMyUnR3endDUlNLYXhJCmhkVFFZUzMvN29lTnFsUkdjR1I1
            eDh0Smx6TVBINW56ZnBVeERhTzBQMm8KLS0tIDRYMlNNSzgzZkZaaXhNd3FmTDRJ
            empXMnhHVGJLVHRXUXBKRzVSc2lVZWcKwsWGq81Hvh9Lm3REeOoNZhLtWvVaJJ66
            CEJedqUcnMuJPrRDVVuIvItVyPu8QI+VMDQCjJ8zEya3Zb9QiJxe3w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T22:26:55Z"
    mac: ENC[AES256_GCM,data:Pn7osjNF9HAsXBZee/4MC8f5IRQPKI50UaHp2Y0ww+EQgVukxmB+uBNAtdQQfmRqBRDIRl5fvNzfdl5PHgqUoZudvWVW3uzuTL4PH2iQvxGOTWoDJ5Ilek/eYuPEyiz+GYad1wi++h6ndISLGKXy+fnGjPPVD88hvnrt0rD2f80=,iv:4C4U6tm6C+f9Z5CVeyPYwJOsMBvrAWnq/Fw88v3FCAY=,tag:9uXmgXB0YYQdI+tHAFPAig==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
