apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:V88OgErE/p9EyvIy51J16DOAb5QDL/faJ2p6H6BMPuYXBSbcUqcfyPHF8nAYqH2tuG5gI/5H59f0Y1cSa4HMGtcnlLOT6l397kXWQ1nAz0rWR94/OjXaSji+OOw/USFu9Ne92si1GcpE0/wJefAEQ/eGOMWjpIRV3OTyiA7J+Mj0OqdFi0Z7XXzEoTpryTlOrP1Q2Nm+OxaB9EaRUnsEDC0AQSOAsVcROIF8Q2OuoUHGqfyEy1uncjr6RtKbVrTfwWQ4X9Psp29PlkCJAn7jJnGlGL7k/jP4Ypkac77zWNkJBeAM6vhAqh/le8Evo/zX+uLgC8ZBU55+A+Fkj4dy8uDGN/ayLc1zeAqa1cylASVo51R591Vi7eRWyTE7/TIy,iv:Jf6in8SAO8KFF3oSyXABQem+wq9fbG0YW75QwTOeKok=,tag:fnTdDNu23yTJNglUSWAu+A==,type:str]
    identity.pub: ENC[AES256_GCM,data:k5M5KwM2dZiXrRLK0nbLHXczlolw3Sqs39sbwpaec/9V0qJxuv/X6aVjd/GQG5Ek6HTC28ww5tHYN0xfeM6632EMZuK+AvB6WHBlevgFIhav11zVX4ZilO7riZqMhXKSXZ5p2fepiu+Hzq6cYpJHMdLFQdXvEWTj9MLA218IN2xuyI54IRozbDb+uMT0Jh4gAgfk5ReVHu3Mk0DJb4bOdtzd+gASuKBTfkm4X2fIgniEFHvR0IuVph1xsq/WzabO7uuZKOessQmOzxqkoQ==,iv:pfioCy9Ljd7Udmw5vi5Era5dd8VWWBT10yxyt0xs9U8=,tag:DsYcF7X2dwygL1kZJBOcUA==,type:str]
    known_hosts: ENC[AES256_GCM,data:yelSufKt52LsWSMDyyLvvaNbTqClghGaw94VK1/oUQTeAyt4eShrzb9fNQ53AfoN1gkyyT4l/cOK0FY471QCp47/+//lwkYpp3uiShrINQKrRgtLAu15YI47DLVdITJYli28ikQiAH8lPKHiy3g7RBS2DxW7acjOLwuZNfBeodH8nJOp0sVuOiu3pOMdBu8NogH17KtThWopqhXpCCtKBOJoqd3VHZExftmk,iv:ok/QGqCttPsXQW38OLeWNwUUZ+jYuDDrwdXD8D2AAy8=,tag:Su4hQL79XZpQQo2ZscivfQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1ahhpeqda220h75jh8fwfptlze88sggr70lu3vzzylhj9phtm730sj06q7m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzS3VtSllqdHJhalNpR1lQ
            b0t4MHJVSEdDUDVSU29qdGRZL3p6TnlJZ3pFClRaMHBIUk15eWc4RGlrRldHSlpz
            OWVzcGFkZjRvUUpnZnpaYnpxSGYyMmsKLS0tIGtNcnJGaHRkazBhV0swTTZNZExj
            aG8zMnllQk5JYWgrQnhKT2xUNWVEQ3MKrkFiKlLIi9NteWlasbKWSjE8bq2o8l3N
            JxMeMILIO3VgvPIlPXZxvU+ckBbueDzKl8PcNYJqgX7Uk5ncqZh+6w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-06T16:51:05Z"
    mac: ENC[AES256_GCM,data:8zkGXm6pBsvzdSzmsvqQLLSvzLuq8Oj4N2HZzhVYdOweOBSqwt5vXlnecq+3otZAp4QyW2VPhtFOO4PEgYSMiMWjJyKWkOhplCn8L8tEbfd4miJmCZgXKRZU7vScIsgM8amzFKot0O2QMr/ywzIEljRb1krkK32v5iXCrGNrvWQ=,iv:aWHfqOiU/fVY03RG3a/qK+dK2LrdNHeTUwN3Z2fUrJ4=,tag:pss0iFDLcLStKcL7tDf+4w==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
