apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:a0ykeRucoTHrSoEtb8Sp1rsPPSHQPamQnhRfJTtm+tGdBnuX3UdcBOFwcWy3KJpqVvEITW604GyE1jYzMYaZOpj28GPtviiNyWP8aQR9hSm3wAA85SHoPgjA4uNWPh00j+y2gf8nNcOWeHB/7UYEyOXGzxRk1w5zDAnK77Sa7qw24XWLUV+OB8JFLWbxuAcDhhLd9RoMC9Y2MIEZxN/kKF+wQF527+sKMeSB0yY5gidil+tuL04fzDql7FYIhxpDBlt/h61NIegQOdeYRh+pmVfzzh7Ck5vFl7zVmM6KPjYc2BVixC/FTA5H9v3rD+23f33f4LUvOeiIaNLU5ij0XzgynQBPbJugIkQb18R6Ouy29QB9/70P9HS1+Eb3ciF0,iv:9w96wLL5n7hFt2SPT5qCpAC6hUoPMmcFCOVLMIO94hA=,tag:dL5q4sFH/bBqTH600IQa8A==,type:str]
    identity.pub: ENC[AES256_GCM,data:vPcIIwGwICMfUsbUOGts14sGIEwXEU5tVsgL0lQXWxMCUNDmxI3qYVynp/8tOfVr4MGn319QJpdNYtELGF2X8+kAXYVPtLvGjHfHWnjqgzE64PipeGbiSdBTxj3czEBJ7sNGlQKIrtuwYV93zhOH6tDE841cQ1t963Jm2W1W0LwPojyfzOjPjfdb88KkzEjHL2Ta/2JOJMLq0cLUNh719uCR3Ajd5dofqD/xx91WqVV0bIDEVovs0cNcWouXigHSy7n87kI2oQjfFu+SEA==,iv:xAAc91G+nSRSMY65MfTT1FlA1+1/lZ8aSDHUV1F8chI=,tag:wyBKyF5vOfTbuPgvA65ZcA==,type:str]
    known_hosts: ENC[AES256_GCM,data:IDslwj97/XETB8N1JD4StRnGMBFDXES8dw80D02zVZELLc4RRNrjBraW4+VcdHt7pLcpw8+8OPZL9P2FtvIjLrm/N9D7TzquP0Vp+xnPcEe4J1CDxdgWdjmOm4vqvDVZiVBUM1I+JZ3jrN4Sy9HFBziruclPVo0ET3kWtsxv3n9950ou4NVQr6IxwbTcaYU1dcotneBGF08PK0cdehJS5p/GN5N/z6F5AFWk,iv:G9eBqPsjJFNpdR7Myh1u1Ke/gpsV8iaK6G0iBVR/788=,tag:ybXR10SV7tbcoopJQXmrbA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1ahhpeqda220h75jh8fwfptlze88sggr70lu3vzzylhj9phtm730sj06q7m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyK0dYY1cwNDZUZkV5Z3JT
            MldRZUoyT0dReGdwKzNmNERCVmNZOEU0a2hJCkl6U1c1b3J6ODI3V2I2UWxiQ1lX
            eXRJdmk1NVlEMEczRS94MWxXQlRoQ0EKLS0tIFd3STlEMnBXTzlKWHZFMnJiRllV
            WjA3VVkvcitKQlQyNzFGeGt1ZnZIMWMKOF3lF+JAz3X3WxiHpmsMMkx/Lg6O4Cq2
            lw+gMrvmqTQYeDtLPhZRxlBxGunOe8lBQJtZIoflFOwrmhsnhKyXVg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-21T02:33:55Z"
    mac: ENC[AES256_GCM,data:YdEpeADKutq0A574/uwjmqoxmB4kPWmFZsPy8LJ/0xUk4LkOZfcR3nyCS960sjanbA6kaVezUrXkH/hYkmnPLfHmNaFXiOpbVw+u7c2EeC7//qckOyhPGCIQytc9tPR0uQ27wSN9yqmf/7/Kc1oUfuQvjvt2XL0i054HFlw1Q84=,iv:6bRJgbPxafrwFvNhYpS4SALRKqE6D1RUD03K35DAnSs=,tag:fjbrk+L2R90xAq5Lytz+JQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
