apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:RQEOW7T8ygV/0goxRmah55neFzeOfFeDCGu/EeQ/I266b4GhWQAF6iTcGov5DhymozLKfShV+J8ogCT6ZAmWISGIpcEhycRlIgaY9NRM+ACbuhak7hRJzeFkzecpPM+qQzkihbCTTJCmrWOjkabFjpl+yIBQL5/TKTbmPROt7Sm6MfLhCaMvsp8y0nwQ7pIVoYv+RomgR659/bJWhBqh8OEs9WhV6zOr2nnAuBTG4VPyASyT7jrkn4XUCwLBoJ3g4Y//LzK4dVF5zXyYbQntgndE7JT6UsrEtWWD8VTJo/QARNh73gfQAOFeBTDNysRprPeVL83uJrXYlIMUbfOIKInXJFCn7G0Mvojz4YW1R27syMLZiqDmGecdCfBOPaJD,iv:1yKB83u3APArhaePk5KG3SK/WKH1sKRjg4+NfMukZ9I=,tag:ZoX1h1ntd2xFiu+GxXHmgg==,type:str]
    identity.pub: ENC[AES256_GCM,data:lkm0XlQZ9m53K1b/BClzcM3AZYIgpQHPipTzk+vC3pkBKkENPDBOVDas3AFPVjZUraZ+QCmjnptndZRXjhm7kcP/fZFkcz5DKk/kPUH5wc41ZNTcCpi+9YXQrzQHoWpSwB2XSM/6aXqPTOpMGIOnXlG/4fgMQ3fdWY5FGmuvIXm0dsDk3Shx66AteRRRkyoa2luzRpLWqXBmlNwDTWMDgKazXP6QrnatEf8yn61qNI5fwbpblcZ5M9Y9ZvX+yleY/mTy333Lg1Ckuydwcg==,iv:NMY9fN3KeAp4/8ZAxzn3T7vcPSIcES5zpa6nU6zahFI=,tag:FhinC/mjtNsT5hMQE6eyjw==,type:str]
    known_hosts: ENC[AES256_GCM,data:3FQmIVbTGWGwmC3tsil34iYJ4OaIcC/GnvoeLzucrT3RtgMKlE6bdCAXBhoEcOX46pmplnoQXpuRRQzcTCI1JoPRNwXZzJKJVRg8XjORW6qR2FwGlPhRr1idrpt8XJbEwe/LaLYct6mKt0CtdqN0c26kbpCCdds/zFyG//zQ3FFNh9pt9qNiHJOh+yjb+13rwtjowmZ1Dfe2Zf/4Vb0p1sO3M4a3qQ5EYa18,iv:OJqXf8vnwuDUjO3DkPdBO655DpBTQwpc5jXJVYQoQJE=,tag:03MH+P8bpDKVWD/WcaRGMQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1ahhpeqda220h75jh8fwfptlze88sggr70lu3vzzylhj9phtm730sj06q7m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1cjFzRVNYL1FIT2lpRlpH
            d3oyVTZPZnVBdXA2YWxWdnlRVkNLNzJnYVRBCk1lS2ZoY1FMdm1vb0ZsVWphb3Zo
            dmZFaEhUOW91MGRRYktGSVllUi9OdmMKLS0tIHVyWHRkVU9TdmN1WW1DOHlHRlFV
            MTZQcmhzK0htZ1pSUVkrbWdhT2x2UncKSG+WGuqLvibT1tjJTY67je8BoAJF8Gzk
            0nSk7lVuEjm23aAuHyrVrRp7suk4BWMZ1SgDoR7wL0jjmRbi5sM9RQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-24T18:22:41Z"
    mac: ENC[AES256_GCM,data:I7vkf45xgKKpK7OobPGiA6RdkZqsBVNDjHSBqHE40IZ5q6d6bpCDRYJTQ3ZyPbFu/Armj244Q56HlKPalRdhXwEzYdteXzqCy7PxzLgu4UpwslHAYkt5SSbjYdhDPKD/spSW5x/AfsmRQq29bPUFU3oMHbyW2iH5nMfLswdoFus=,iv:9882wlIVRL3QQyccitmwNSmmM8NH+wpO09/BN/oT/KE=,tag:1A6ejcsEm1sZPOBQ+ipbjA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
