apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:FXzvWgzBfGtMWsWtb+Rkzd8C3S7N45qMVnCJSnJvNaOZh0wkaD7df4h1wYP01fyLvPUEG3vOeUEIn4+RaBA2aDjIhlX18SoDVSZpp4wRwBgT0zHBrN/0Ji4O0va2lhAxIGotS97TzRvQZS+1jzBf96CP88QTBvFBbGUCkyo/lqN+sLct4F1zzvL33qeQCwATpWLF4aMnnnp+gfAOZ1oTNVXMexiJBWI2fzEcEXmreZeAuoChVru2Oc4TglAKKS3mgmeA3HRqkgxgTwDmjTZqQtazuUqSsE0LVuexskMJCLgb5AhdUpJG1Tx+NN+l9Hv3gkPwMw6iz4imb2FGdaYtGNibSzDF56pdF5coCCFpU+VZPONBveKi7b+L9IZE5jWr,iv:ARZmyjxyhkyGrN7qXKjm7jHKmG6mTfEu2wshW7vv5SA=,tag:PFgT60ZsrT2j73dMybr1Vg==,type:str]
    identity.pub: ENC[AES256_GCM,data:3UKbYRbRvttVUPkr6iGMNfFthoHxmaTIp5rqzT4Yvd/lP7+LQ1uH1tO3t8N6axw0ilhkNUgjBWYQjS/v7+zfgKvVwxwEw+EjryjYIlFgIML6d14sdOZlJsKbuE/fQr7BA5dqg6GlUEsjseLgWfevRpFfDzsVakS/oLa1x+LPk2BPiCc5IUZJH+CcNG2hh1VIX7aduLRU2wEDEN+vvbFfyC6I3pbUD9WrqpjGR3iW5MonSPne1ua7mANEhpzDSkmhfR6C7X1DoSd02vsVYA==,iv:iHo/4gg2f+QmwNnjx5AzSC5VHikFmPS4/Ue/FKxesxk=,tag:iqyZIXA5d5pORWs4aekKPg==,type:str]
    known_hosts: ENC[AES256_GCM,data:kItMp1L7UoFiUJPtpq8GYeIuVBDXY/CQHeuNScBcrSP3DOQppbDek4kZEcLE99NAqITZplbiPC+bOfJYng56ubg/sE9GtU9Y1zQYvOr3bl8pVlMKwUqFRphg4qAZdmWihEYAdjVz12yqvx2zH2AZByijqrsB/cLUoQ4qhAMrfB4Yk2t3POT3Kv0R+gveiT3elsaWvtl6kU38FQ3n+ClyoNIwzYxo7vbRhDSE,iv:eE//9VcGZgbKQuF3INweG4ajc9zUVt751+Obie2hb0E=,tag:RcOU4Puw4twA5n5XsomgNA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1ahhpeqda220h75jh8fwfptlze88sggr70lu3vzzylhj9phtm730sj06q7m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIWTkxMVdSVHNrOUtIQVB0
            ZWUwU0pxdjhDY2tlV0k1eXZ6dldDZmxFejFBCnhQZVI0NVBDMHdOL2tvQ1pqSHcx
            OUYvVGZBU0MxL0hLc0N6UWZWb1FqQncKLS0tIEE0YW1qK0laMnl0TC8rVkFWVDhw
            TWRkTkx5TWgyc3dOWVJ0NW5RSVZTT2sK/sTUONIzQoscfeodAOYfjpm+jE0QVaxA
            YKh/NKvSmyUYpIeZXIMVzTWNrqEcubW3ocrw+fMyubAQvdF7fcnmxw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-28T22:12:50Z"
    mac: ENC[AES256_GCM,data:Th2peWmtuqmCP0MhwxeQNt8D4hFQG3sGQBNkSimr9dho5KH4QfoP/P8FqK3Zj9wGNtUpdnwxsnX+rEzZxQrjpf2e9m4kVbR/flICZmXYUFzXZmy6gVDCFk0/lw2DbJ+lBqCRMB2g2ddugGhX43iGjQriQf2WbEnPuQZ52YYGj1Y=,iv:79F/EEyF3ZSVQMGXmRoamx9vlPUOz0O7zcQcBZAJITo=,tag:kSLnF0o62E2sbfPh5f6HVQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
