apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:uJL+C8HUXrO3fJLWG9KAU7Y9bY1AIqIFpoG3ZAs84XoaurlXuGbpSzdf+uNz1wTEQIXKUT73FJrjVg58PwtMDKhQqMKxnWabr9+LQfkzylYU+5GKUQpFuKvoM6ljIRH75adUv6av4LknL71ehNppH0m4Y8m8ZGfMUhyE9FB9qtGzUqapxrrbFXNlPGNssuZHxQGDfrq8/zExFOIlWvQ9PCk/LpQsBXU/A+hvSc0GVUhmbMpNxY2PgalNODYKRBCTWJTauZtzEYiVivlggeTIBfnp54XIC9WYERsu5N+msH2S0WXnEmCRwCFKcoJQzDzFczaUX4Hepn+v2iZOJVFzfTSwO12IIxGAvX8Pm/ZehyWlH+mNmfGoMAlDILKNIqSj,iv:rx7p6xBRXZnKANcHMQq3J8pmsXPwbt9hR8kBMmOjHxg=,tag:Hzdp4Kp248GGyckGlmFnhQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:Zy2qDhNlP8y1fPRJhJZ3YWN//7yByk97B2Aq+VaTa6RiWY5luWci9Ila7niNNKu1sv8LOvgf8i36WQDI/laXJgITAIPCRRxSO9tsxCgXHtThhr+MfWR734n7RM2DCo910XAZa3CLvgz1eg+B1f2huMeO7AfCLieVNp6GgJljBGZZTDd4iowHwLvW2k4PT5kiBPAeESfroG0ZGGdJpPZ0xmR5wBFxBSwoL0A2Gi5r5EBTYPpG0cDAMFN5BouK/bw1X8jquDvSkHih+r+X2A==,iv:7hOzAoNXan+AmCp9XFG8BbYQDZwkqr+EEcxPPYNkKgo=,tag:8IOaiAE9FHbzTeSfF9+9EQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:DfxSZ5O8YTXtTJXGOqKX2CWtKh7+dGWRTAoV05nohUur640g0eLaLL05Ru4OtKl1ETQn5BadwB5igEdt2SIShhkdz8HrwSjiiUo+ShzD+/Mm1jKRlKNVNk/lXiaZxr+ewF9XPa+COl99RWDgSKb/gw6s6Iwanwm4OcAZ3K2Ri4iXtdaa3TeUv/GT1JO/tC3hgITngrqKMPidPDspC02u5qZc8cYDQdsy7Q/X,iv:nwmXKQ6Oe99a6GaYqwqj5SH67fmn5+WZsbdquYxKRnE=,tag:Gh+3gzEm7m8c/vYR9Tn2jQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1ahhpeqda220h75jh8fwfptlze88sggr70lu3vzzylhj9phtm730sj06q7m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCL3Y2aERyRzFmWFhEaGlV
            MFRGTXRMbnlNWUg0TzVhc0dkcTh0dmhrU2pBCkFVQll5NFErdnFuNjVqU2I1UlZJ
            WU1iOXdTTTR3RmpCeHZEbmZ3dHIxVzQKLS0tIHUzckNta0hhUEx5blJldTBKRDZF
            QldLbitISVNrcDBuaDZ0dmpHMjhNUmsKVN+E0jCyimxDv26/qeaxThCJLv3+hotA
            dnQtLX1M6/qDBSTZI0Nla1U9KlTBr6D3qVIbYwHwCidIOT7UOuxMjA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T23:21:49Z"
    mac: ENC[AES256_GCM,data:/n8XyQYZz4NiDKcveRdVspr7fSAvz+oBSoCxZdBcs0WqIfHKsTKi49H6Uvasih4EexUe0Elm7bC0pEXJaxa9l+dxxvFh6gxssAg1nOkrFYUQg0HO71tii+Epk1/HzpKrPmJxH7wLSsAWXFubtQdgSyduC4SUULBEyMYJoUA9Als=,iv:uFrYLkkb88B8rrwZyFCo4bgFkmEo3zp6JjhTZAJuljo=,tag:FNWqjj3OFqw1uTfh1qcOYA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
