apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:yk9UVHWX9Aehh0g3WjjBLano16ul/kJj/6fqFw29IYOvkzBELokDI/2hmOLNwy8Qa2jgzGnlFJVTyddk4gm90RzgD88KLY26nVP19ouEd/kqwh7AsXZhvur/iAiGvm+Dp6mElUI6AVrsMOjgjne+khz5RWMPz35CV9ekUgtNDDyYqzPA3ymkDnlO5DGkXPgADH3wZ5/9j+TZNWfX25h56TcqMvINnzHCK4GY9qwnTgbAvV3aznaNAXr0gVxJg2Ho3CPaChUgP0vRgkhmFsKHqtpbZPtns7NRDEWx0aQ4M5IWHZuBl6LNSOB7F4oeqIJOiNnBMF63eU/3X8eHU77GiHgNrCSDluYtDTzlSMfJTNe6+uuoWFrk0e5QwNC+uBhy,iv:P5YYnVw6GapP0kvrebdrIdjLAhVauCR05OBH7otjjpk=,tag:BqGpnliBhw+4kFBvWvBxyg==,type:str]
    identity.pub: ENC[AES256_GCM,data:QQULrzuufAeSCol1Zdz/yItIkCIVnuoAqrguUpQlqMAgfyFYZlnfu83aMznP+2Bf1/fqgxXJce4HGxNJUH6tkxuUAuJK1SRd/C/CJOhI6qEws0eYDhj8ti37KA172JjTWQnYMGShWp89Q/40YgUGkNPmqjo+mFZ0YQjsqaWMSUwUnDSxLSda0taSHFSZBQjSiM7ZW7tkF4C6X38ToeRUCRQ8AXLDAw0JZDu07PD/IB6dmzWiNrzp9qNH5Ue2Nhx/coZaZ/eJ/lQrTEoUeg==,iv:/fDbPS1h/6eSOU2UwkdmHwNiWnUZg265mg53ssRpit8=,tag:Il7WV11DtEiNagTCg8bxRg==,type:str]
    known_hosts: ENC[AES256_GCM,data:7US3j5oNO4sPhY2mpaEHB72T8tsRzfRFDXJJ65XAwTeP4RW1jYOQyi21o0gcDCgwED3MXTAyGkncFiWPQbGw2rtxVhsFxPH3QGy91PKnOqNI4/hhciJSt+1N4MGIfPDk95BzJaVMWwOkIgsSCwmaD1xaQ4lMBwoTdhnPLyvMl80WlzmLYsd8rE2/QHd8ok9qhWTNgNK1rNi0ZJIkPByhpZw6fdCXU9yVZety,iv:8e1tWdF7thRcqzjesghJwjwVfWiZgNJtamtbmTcn3J0=,tag:UU8jJoW6b5gO5rTvGcwJBA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1ahhpeqda220h75jh8fwfptlze88sggr70lu3vzzylhj9phtm730sj06q7m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnTmdrV29BYmZYOWNtM2NE
            VjFwWHJvSHJWQUpzSFMrYThTS0R2WVYreHpBCkhZallFbXphTzZ3SmVPMFNCWHht
            TjBCNnh6VFJ4WkJlUkRHY1FPV00zdWMKLS0tIEt1MFRDS0ZDQUZScFRUQkkzNGl3
            U0RSQUZiUDFhelEzOHpSTlJVMWVqdVUKrrsEINuN/4KxpxOnub0RQAyNAM1Z9Y3r
            UPcgkV96cZJkOhgeHXEuY8IJur1V/Ip4OjYbtWICWdq89oX4vuBFvw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-24T14:46:06Z"
    mac: ENC[AES256_GCM,data:rdRPUDf0wveaHCnMP7ndQ9WPxZ1MFXiQVZrir7mEUKFtz+x1tcVRn1LRZFS+SNWpbEn9NE1fp4ZQs+nkR153Two2H4/dH8xWn5Ixzu6BfbrMwrwuiMTMjyJCN+wJdsUVFD3vY8h0wrhmaev4n6Z2lZVsfXuWblEZAMgKwigNDWQ=,iv:6z6BakYc86oFUK+qqERHYQgkvrQUAQUBQTcIpMIe+fI=,tag:vxz7PLUt5XX/G7okmKfgjw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
