apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:TL3XiElZVAxrDDpkzrniFYOlI0QRPS0xtj4fslkOZimrDAqK3bRNiql2v1kaJd6BEm1PILPndwLDJ02BPqzViGHOYbQR0+io56v0cWnhJsGQs60VIyG+SxOG19r/KdfwEEGDeQFHkTm4btJRVTRm2UWWcTZg9yI/ZdKa40G9ksam0z9gQKswZQEVq3j4s5/Vq0x3oowrTknW600YRqO6n0Whh7oWkGpUxI8cr8hcS9eAWHzPkgsf7sy6UEGT8/8qoGocaqPPKW/xbyy+iKtHuWA6KW5C9+ANyJ2hpXoCbALlYQipLTbPbJzu9wECmNpBbnqUmLNQM5sK9wh4AwEDIrJnv/2cHPL9ysu+HIlfbHdZt92POeqpC4bfli6l//rV,iv:ZD1ZB9mCyAe9Ny2BkRVeuLIdN2dqmJNl+go1IX6h/+Q=,tag:TUMvbq/WJHHZr4KDRdYlPg==,type:str]
    identity.pub: ENC[AES256_GCM,data:ZfgqngJyAmOb/s+T7SH7KhfhODMsWqBxxf68MraEiwb6GIkk4l2f/PuYwZCd2UdIpSuFkp3F57p6O73dD0J8pG4qVN/3irMH9PsKOnXaT7yq+F/oqxETkUlhHTT/4dJJN9rpXYQK9t8o2MMO7ueK2ghoSLoHvojUWKN6qGd0g1JUZak1QeA47Rqp1rWKp3g7wCHPHmBBUE+/f49ZYBvF//beWFiC9k8vjtqpCc5wdOpDERTMLW9ZLkGwWIFHknkH2H4odvt13ekAHsCxtQ==,iv:ZB5gnUQfu/1YQ4EmPrDxKyUwBu2KiC8hN6zYhIRXQkk=,tag:Hr2TLbWXpiTop1XyRkWuSg==,type:str]
    known_hosts: ENC[AES256_GCM,data:Kh33jLiLv2cYKIjVSglIyRw1iKLXeezouyxLdfKbi9cWzqKqJ07+7fwQiNwFvORU6v5zvsLpeBRETL3EABzOsazCAbx/gmGotIdYBm/ncebCqGrpz747q+9lVIMgRjC7uDXjRgXm5dEzFWHt/nE0M6Dv/EcWuoN4ACuvx0VPDBHL/zr7LExYzRXQZ5KM3ic3PByYBjM+zK4quAkrTYMtgzMPD1aOX2ruAnEP,iv:tC8xyRBw4TM6UysDejdcAkcbovd4DA+5Ok4WLaTE3CY=,tag:+0CG0UuRB+H1f6/sedieQg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1ahhpeqda220h75jh8fwfptlze88sggr70lu3vzzylhj9phtm730sj06q7m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArMVNYQXh1QlU2Y2hwUTdw
            ZHp0ckNpQm9MUTMrWXBLRDRJUEtHU3hmSDNzCnFCWWpWUEI2WFhxUFhKM2ttUi80
            d29YWi9ZeVB1MDZ6NDcxTVRKMWlGODgKLS0tIHFYS2pWZWhQVnYzZEJoaTFCeWhx
            TzRxYjRSc2dZOXdSVjM1aEp1dzBEeFkKRnbQMC0NP7fLy3R0ZsTRSd5im2Dn2cqU
            UhBWkKiIMyar74zrTbfVgs/grHZ4uQSF6543GzSzaaOkCb64FrWQDg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-27T01:18:06Z"
    mac: ENC[AES256_GCM,data:0ar+asfKx3ICxZSrSkY04CkssxwTBSf9zzGQKGmwdoCTVWFek2HUpoJkqKYd6dKTg+TRnnDHP96gwSb3IaDvPgDKTDJfkUWU6RC6Y6N1NSQyn57cbsX5xI+0sk8mZ/F1B8YElO80VjAh/HkWBqPh2QyJnV38GpXpjIly/Oxx3kw=,iv:Fn4Q9AAsXnPFiqAly5pMTTd/HfnS2wocKu1bmtPMxMg=,tag:1/HcKR0DLi1qEL3U5tXMFA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
