apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:vUMmRtaoVbs61o4w8k5i+O6XlMsI49ePmKWRRKZpvh7aM49quZt3trsi6Iwnxl5UlLPLev5/4MIpVHP7VWAHRE6G3REBcZ5h9j7waaL7Hnd347aU0692EE6Wz2qaOp3EMk/DVdSjhtdp1+lhX+6HTu/z1dxytzQjV0ckATi5UCzdTTUeFSmsP1LdkMowXbjApgg+wyi+ybfo/OIfbYZpk+F+E6HipPJ1SvFDC7GeMIqCEutuGNhBwp68eR+8eN45RTNhcnjfd0TXIWzy3JCF/QANPBVdOBUHu6YgjNVnKBZ2QaWrcsl8wLEBzW25drISM+TU8TI8gmJXM6PuLuGbOBOcWUR8yLXl3oyU3OXZlry+IEbpAKatK6/0+Ksl7Kdz,iv:fpzUiURuO/4EJY0i8vbz60UMctcKEztfJz4GPalW6GM=,tag:lNeawuwoHsBA/HURfACb0A==,type:str]
    identity.pub: ENC[AES256_GCM,data:0ovIxBra3C06ok2XyY8mA2AuNdeRS+VwnX+oNzxu64Lz3u48kRVN8q2xo+0KJI64z+5DUNsM6OE9DUG/RSg55gbcOA28QIKbUtn3DA04yHK5/AUa5HPrmCTSQfZbyVNcytOHFzz9Gphho/iN0mDoRVKLxb4QXJYhCtWC2eBYa18HkUtoJ0fDXpeczSK+7YHcO7EYVgdcpMw+BF3ET71lTT67uRQLLndzqHHZi6Rg+5SVITqQ8L1LIUYo8nRUdepwF4Yu6jGgTSRLDXNy6w==,iv:9CpCkrZYL+CxGweR3f+x+WsoGvshmDRxptKHYyY5OaU=,tag:BbWF1WZwcFgPzii3Pc0ONQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:xZQ2zKyJhSi4FoxodKdsVh7TiZ2VhzPNDcCN8gIWaDdtc1/66QAr4vo1VsY8EnOq5U4BXoyfUZhVVZHFN1vcGko3MZipepSAefiuCjCEGlrcDP5Xa7KQ9x3BPMC26PyLG4/WQOSvKEl9RtSTEyAv5gdo06lc44ERIBnrQi/ZoVUU/Y32iaS67sLUSJ2FLh5P/q35+j8hN9Lcvj+KvXA9du6JQFEvJ4ZDsvlp,iv:CiYr3maoxREZPrxa7MMHDbE9vwyv5GntgdIm/tsucQc=,tag:+uiza06TSroDXacCmHXWIg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1ahhpeqda220h75jh8fwfptlze88sggr70lu3vzzylhj9phtm730sj06q7m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBubEhCczdnT3QxOFNwTVBw
            OG81Q2VMM0lDZU1SdFZiMHFpRS9MNGRPS1hrCjUvZDJJcnErSldLT1I3NEMwYlR2
            ZXpjbkgrU2VrOTZ5c2x4a0xlazNRUVkKLS0tIFVBN2loUnNDT25SaFE0SVYrRTFl
            UE5qNVh4RWJ0NVkwS1g5dlYraXNvOFUKA3dh/DEjzW8fgVfU0hYwnsCWUX+eXpc1
            P9VmHwugbXhXJnX+TA3Z7YvJI6NZRkXnSQjmE2GJOlJgNCvRPrtdoQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-17T20:14:27Z"
    mac: ENC[AES256_GCM,data:VysyjgzjVGTWrs9SV3NsO5INLmnTlzuiUS4RxXKk17f0SXGzBjt3HnHkk97ur7wbJUVJpRPAx0cR30PGgdTJGR/vqWT8ig8UbXIieKEyu/zgXjR9yoxxvNEM/HSj+hDJp1ZwtBn0Nhg9RvqU9AJBVSi18k/89ET7bkXWbTTzWUg=,iv:3IwjQfx+LD18Dg6ugjTCmIMlTciwHot7q6RETpW2dhk=,tag:6w/f4J1PqXQI8p1mDZPcUQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
