apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:tha0uf5sN3NmCdMgiSdKYAw1rCUacTT8Kenu4Toy4zmkgFHM1m/rYW3GGYFyCH4UnBjzVhKm/9nNUlG2uUWrz/c7LfWErmDhkbOcyXwMkGQ60yytRYJkdSGUaUi+wIKHy7VDe9J4IlcC+kk4X12AfI0NxInKK02u8uwNOWzKjm8rs98ZgiMKW07Tg+MgtDCFMU2rkFJNBqNl2cW5hzhIYeqzJJMDwN2VxKQzCfzM91XjDQYJ4cRcyRRvHnu1IxVm0Rn/5cI8kJrHMEQqJxxhtL/DCEa+Wr5HK6OtW0X303ZomAJ4Ae4foTRisH2KOjJzURmQG3iwYDhMZM/6F2Y57GWP8qQl+seca0Gp7n1hPtBc8g2DQocNTqCo1fJZHBKZ,iv:hONaFKe1uKyljGtQyLZg5EJBpQBwu912nXhB525zaTE=,tag:etA7dlSoyapvezxI9NB1Lg==,type:str]
    identity.pub: ENC[AES256_GCM,data:iKdMXwC/cIrkIYO1vE5onmNHnq5yo/8292LtihsB6MrUjR5ojWEKt0TXC5I0Q/SMEa1o8nipim+zkx7BHd/tDuRJkOoIPPW1bGIBGrZle7p1h0umRz7NNIwqPo2KRbD2A4kCZ4kAk3A1tB0C+x57doQHkF6bNTD4Xl8pH/DUBYci7Rtk8NLmqhzSpDn+2Bi8QNlA0DwxpdfaSRUk7xDXn9VbuMdFEEg4P5w2ykXLXgTApBIT8+Wo9S9BwPeHOw+PozmgoNjdkXbf0lJ2lw==,iv:MU2N27Qc9VlhruE10Kyf2x4V6o7Z8YXau0r31KObUzA=,tag:sH5o9lhlWySqXOsVgVB47Q==,type:str]
    known_hosts: ENC[AES256_GCM,data:7Ee28sUXTvrNXXlmIo7BCaS/4OQA+0qRwxRc4aB/OiXOA4WhHdb1sF/x/BLhi4GnwEk9hbes+NjwdcVmRPkaGQP6TGGp9aJB6Zyplhi+3zvAtV1wZiye/wnPqwxsuQByDxsOC33F2yeqdFyJ9mZvxpkga3iAGJlwmqSTTSQcQJH7zX1H6O9ZTr+ojYjFuUnQgs9MzAlFWDdmEoJJJ9HFHMA6Lq3fyfCFa8nv,iv:3Y0KoIZPKzlwdP1s6US0dEGEPFs/gu3v59pbW+4DTGo=,tag:X9hgaCUL4Msoh7nHr9sMZA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1ahhpeqda220h75jh8fwfptlze88sggr70lu3vzzylhj9phtm730sj06q7m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGMUsrUCtZSS9XUWlTanYr
            amNnRzc4QmluYUhXeHdackdyYnBuQ1pwSUdRCmtVWHhYUGRPWTdMMWVOUkpyWmpH
            d096WXZZRmtDKzhYVTl1TnMzc3RiK0kKLS0tIDdvc0VqS1pYQ3NhQ3RGNFl0VEpi
            RHJKMGdUMS9JeG9HczhKbmxNOHh3eG8Klsg6bzezFfqINKkTwV/Wr/kbV1w5Ulnt
            cOJ/zlsmOlNKONgPbWl9DMmwmhj2YB6HqXpv+sqmuSArIxjGH9/0dA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-19T16:14:34Z"
    mac: ENC[AES256_GCM,data:qwCkw/qX0nE1gHacsF3S9GSydqhAyOix2PE5kB/y8Zm8FJ6IoULOHUWgpj+8gTfPHI6nKWZiRFi5jxN3SlnYC5fobkY6qA/z8dmnSQI93gSLVibsIe7LxqJZWMK06UUwz5miecgiFzn9TWj8V0lokveBYI7Z4YWDxL8Mk9A5YNw=,iv:w8D8wFnijkmzlJ3B2/LEUdpIlCbINCW/Or79rjrVH34=,tag:BFyCuCbQ5TXfQNhEossp0Q==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
