apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:pCFQ0EiQHVgaxgrkea9I7l2G/GG/YpeH3bnjee4ZvJthdovajPJBOEDdsQR3bysmHakLLvZoOH2H6uLuMBpFas1dDopAdzikONxhIWgc02ilI9q+7jABwyhnvjGrm1YdT3nGsMCvQIQrWwolX+ufPwKhrfPBLJVDFd24UFdbCjS1ETLT8tCHFh5NwXaANLbGgikDlHD3lpH4gW6BkAmSQ25P7eITv5OBfRYi6xzJfvG7HGNdzYaYjlHtG36NpCSisZ5wZ4CmsFk1hz+bRn2Le4nTTCF1GIBYUM2Agon6Xd0FJwrtY8gfLHci5fyBouJ5omkPgxlnAhG8N+egatnZUrsUoCwJPxFaAUK9nNUPkai2zfpQgZLrAkvcdW8TRVIv,iv:b6tlV4h7egWphuFhn9UdiT4nV/I5haLLTWCLc8vGkrw=,tag:ozOTA1lqAQCHPwIYcHu5CA==,type:str]
    identity.pub: ENC[AES256_GCM,data:smQQprNx5J9TSX97ptLngvnCX7UAjWdpts9TWt258Hr6QI5tDOQFN2mXdxWiVxJp7XBuEP6Msv46ci+nhUPPMgQUJhn33GEQmpwNrRL0+Rf8cJYNHGu9UGIXinjInGT1P6ZYlH9XrDzin5lOz3qsad3WhJ3jzVyQCdG+Igz2VExv9bPaAUo/OmnLDyUe1EKudYfWJYWanKo8ux7sBvtVopo9focpxL2bP6woOkHzzvWgfz+bh1qwKVbQSdub6MiTQs99h53LMaZy/OPlpw==,iv:p7PT/D3fIZlahPB06PfZZBgIji5caw4sa83+IZ6Rn9c=,tag:KAHPFCW99S+iLtQoXlF/xA==,type:str]
    known_hosts: ENC[AES256_GCM,data:unon99P6PgUxKxD9iUh/xtCGda+CyEUNtMAje96TAC/la8ghRzPqudKSDaZZ6OJI8B5O89aDsgKDpIPwFL9+V1GD37XAgWuvyQGq2eny2VyX/UCNt+tinB3qrTIeig41rQ3nZn8wfBG1Q/lxSF6rm3PIWq80Daeao58qDZgd6ARkRWqjBokaWlYzEND0e4fzCrYeInYbaePVdjfnbNQQbW1oSnivIqBtdGIi,iv:ra2HasKshqFU9AEkiWDT5RGp6E5kesMGAOuc/GMKCcU=,tag:doO8lZL/qarDUUKMjkAXjg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1ahhpeqda220h75jh8fwfptlze88sggr70lu3vzzylhj9phtm730sj06q7m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrUTYyZXBUa3BIMFh5b0lK
            ektXdTVTRmtBWTVkdTFaalVjcDQzdGdzR3dJClp3clRDUE1LWDgyWVFJeEM4VVoz
            QURyRGNMa1NFMzVmMWVsbTZsRlRHem8KLS0tIEovWlAwWDZ1VWc1OFpkeU4rN21S
            aVYxYkFrTyt0RC84VCs1OGRBbURRRlEKBYtTBK9j3KzbWx9ELYlR2g+h/aiioKMP
            4Kzwo49Bbvr6XNJeSXgzay93cSjxn0PMkCoNkpiZA88UylhiL4WmEw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T22:37:25Z"
    mac: ENC[AES256_GCM,data:Yr1gebK9l9tE0lzkucDJvpw7i7nHtar2dWxl7G8pbh/d7gNecpKkpPoEAnqIMNJ+QZ9w+63/jIO8wGoDrTXsVkwvbC5k+oq3aULR/sLVTfVXV2FXdjGp6SlGtHyX9Ks48izZyTwlBUdgXZR7via5QbJi6gtnDDq/L+FlfEKaXOs=,iv:H9VQxMRVVCqnK3kIfUL9QbjIho+Ewq7k84fxHgS7k1M=,tag:JE0JeYcp/JDCPl9/GTdHnw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
