apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:yZHXuWR/joPxXDxgYvcX0JzWcGVDZOzzXyFeK0jHtk1gykQ+0uSPGiDQ2aqtL9KrP/aVkjxssvnfm5c58m7ZnfYDZJgOrqq8W2DhloiIamVTCTXfPiNePKevDL1BEi26/pV18wmAgEYYIFY+5synOAl7Cn0BdBBhBuFx0VV3k8f+yLWRySNZ/7dJRbVluaHsUkOCPlm7kd5xh1+5JnCxVpmG3CchP8PVKgw/R4oTFv+P9A1Y8NLRRUTr84+fOsg2H28eVobwIQ/vpfvWJL81/SQcgSpyWnj7MJVfBQ8KBMaPP+6PJ2OjyRuaaSHQU7K/i9R18DurO/D4w7tc+q9twa758lgmY8Quy07RDXbpVOmFBU8viDNnaCkSgwXIlTqu,iv:9yGflOWSaeCGjhSUpS3RQKhFFLG06jEleflOtPBKW4E=,tag:i7qwQTDCW1SOTM3wD1+Uag==,type:str]
    identity.pub: ENC[AES256_GCM,data:cc+AmxnYhjCXOjj/8wW5NRvkwXwpSuaa1onIIJLDtbkVhgUya0H1If66h/BI+cru8bHDY3GKyrB3frP65etfnCAlnNsDbkTIKu7a1C0UqlBO0gjYMro5R1ILawSm3JkMWTptIlLePqOyq4nsTPvjy7V9UiFa3gK4eO9p7wZWx5sXXTIR3p1T1SUTLlq0hrzbSS0NnoTBOZBux8NixuqI84APGuQIRT5CvXJ1J2TyPUh6/KvKfsKTs1sjao5GAsYLMJWtfYYDCQdFf+UidA==,iv:eXbRU6xgn9jJjpDPHh5nguwrHJAlLf7riQYFK7BbImE=,tag:5vQv4+FlAuIap+fsW/KK8w==,type:str]
    known_hosts: ENC[AES256_GCM,data:YXPr+yEf3yX3IlC7olCR0U1OtpKh8QQ/2XZSsF0QypYYc28fOnCL/0QumgFP9kJaJnIMsdWY4GFrP9WFaMKOgClk2eUYt7hOP1Ui8ohoOzsgDS1XDZpcrDn2bBH4e0Ee4/BIEMP09IfMFIgWwhtqKfImhpeRhclI16QBIVOV+byD8448zxblginJpr3ocXfbrckUDEG25WfcvDvUtZz6Z42+rAVKW4klbH9D,iv:q3+QRtPHZWGQ1jDsW2YseEYzOH0tU6QK6C66A3SaoRU=,tag:EYaUXtpzU460u/BzzCor1g==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1ahhpeqda220h75jh8fwfptlze88sggr70lu3vzzylhj9phtm730sj06q7m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkQ0l3NWU5MUM5cm1adTYw
            ZFErNC9QWmo0VjJqaDd5RmZVTm5CUFBvZUMwCjdLLzFXWitMdXpoUmxVNU16QStD
            UEk0czM2dFJzN3MwbWZKT0tLQU1sN1UKLS0tIC9waENLcHllbDBiUjF3SkJwendC
            NG9LZHNUcGYrMFJudXg1ZkFyQ1lrN1UKSGHRs4YOfkdjYggoal5EgOJN0UmIUkk+
            a2sRnmcPHneMD3pOMJ30O74Go9Ryfev8ZYf9ShB+O1zyQyQ3xMLXfQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-17T19:17:40Z"
    mac: ENC[AES256_GCM,data:hIu6LTNtOhp7g5PLkRpWGUJW9CeRb9CyLhbjKr5vuzsI6w53Q4RUXhLCtVZgzUcnCYJm0u/M+n1sBUayZYLIQDAkTsg3bZflqWQAexgrnEIIUm94HsvNrzTfDXAmSHZcfpJi052vLGf3SVDknr03nkxkkRkkZ2YR66Na3DOqkZE=,iv:lYb8sJ2921XKI4X97ejQtA3a3g98plFsH+MKa2EIj6s=,tag:aZH+xcn9c10160cs3dVNlQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
