apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:lvPMxG7fSQOGw9hVAaQ1gPhQcl9mNgHY5JNah7jfeR2kgiPAdQISwNonFbzdzkqAJ8ezRLtplIPOAUJ5KfHnCzEVc8Q0DU5mk22hOBBUivAZ1EpMhtg+LkI0Y+4Sctg/N0hGsU8AVJQMHN/aQaUDam9m+T1SdUatl0Rah8CQU+KtKH2XYnTX4AEfctT/m3YAzaBGIgz1GJGpLSqMudnjwMkenJ20Z5mpPefPaxQvqkKRCUk0av1HD7nUF25UyS/XijDxgyywkZQ9Ky+SSeJZmguUSigKqczrdnzZW6UxhubG7zL4+M8DxV5Xwokhq9CzilH0qgUVIvyHrolzJQ9sni3jgi23o+pXILsTP2qBPqsggGVO6kPMbJvtATbLDZnx,iv:HswtNAFKuM65BSnOoE/ZJjAWifxpj7bsYb4rfILjdfU=,tag:OOXKAXl6w00eEOCC0r9NeA==,type:str]
    identity.pub: ENC[AES256_GCM,data:lTI+brQixBb8gPwju52KZdX3f+4AkUy9TLAY4RaSG4BcT36KzauYywe5PBHbWaJf0ABkg3QWUcWsJQK7NZRer70h4Ie2RV6vxBcaE5i/Jk/kg5NYD4NBhsVjimhw8UyAIKIeZ+WfZyYqhl+BK4ldv1kSa9hEIep0jnPi+eLdcPnQUFXAyVZ+iw/woAKBr5LgtV0oBzSOBagoucAlL9LQgU5ZHl1MH1gRES2aUPbeZkSpCBepXMOHv8JjP9u0GMVNLlnfiJtCKrQQP4/m2Q==,iv:BTLHIZsM4oKjbkyj/Hg7qmWVlQ2tezd4Gfsmwdo8GJs=,tag:39RoxIs1OcmWBp05um1i2g==,type:str]
    known_hosts: ENC[AES256_GCM,data:41GFiE6aSbWPB/madBuCV/KqAkvd/Sy38RgFJvsvbnAs/kKbSGYTsq4MygqE8c3pgNihnCgrjrmznPYih49X0eLCrMSufil8nCpz0cmgcyiCnFOo+HHgXWPmH8Y8dGO0/BpyP509ANLx3np94SOanaICTfVUl1I0LrILawJa9gqxrVHfROkKQEq+pzIq+XsKMvhX6Qq3Pp7tBvhqW1YPGhar0upwcLr3geGv,iv:vh7AKZjlW9N79gcwV8EoGSXcc8xnEtOSg99FQa5CCEc=,tag:t8gLSqRqZqqwVAhfNEXm3Q==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1ahhpeqda220h75jh8fwfptlze88sggr70lu3vzzylhj9phtm730sj06q7m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMdXptcGduaU9PQUxYTjNM
            b3RweXZjNzdLalRoSmNxUFFoUFZ2SkV2TkNBCndUcmJMUDZJd0xneXB1aWVNQm15
            NmVoVEZmVk92ZGtHcy9BV2UyZXc3aEEKLS0tIE9tY2VaZXZNbDFzSDJEOHJNNXA0
            dUFBZ3ByZk9qcXlLODR4dytMWVlJY28KU52smBlw0FAbXsqAYXpJTxw/72ISts3b
            s7ovVRif5gzkaDnu6t1TAMN8GLBOXD7AM2neBduZO3cyQOXThn82mw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-06T16:59:41Z"
    mac: ENC[AES256_GCM,data:CVrT8UxevcdPQ02Bl+KPfBLud2mkhQY2nD9S3WWiS8DKfXCOyzOFXUU3OuQXAjPZD3alzRcxmE/6SHF8ILATouZ8B3H2mOQYGgI5qd6MTc56Qg4sHq/Rtk2VqhujSNcLilhYrMy0PrJJyWn1OOz/lor27QaKw3cfpxD2DHOjVOU=,iv:ecMDTZ8J21j0YFinHuK4BEMKLmLvd86CqeS1Ud7w3j4=,tag:YMzc69ew9wxLGvGHZZXIYQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
