apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:9R9bctd/37Jebn5KoRzrpSqxSlsS2cElUkNZQzJqXfXmx10v5wHwR1QFWK5llwT8NnxE7WpKnuHAuQLC8joN9U4cE3goOZJ2xuxJzgeXBg3efNkFTcZJzd3p8tAHmUknyQtrjLzRxGS0HxPy+qjrFJzvv8btGNd748GuEXpqULS1F0vwDonC56sFQg8qKqzN6wx55wuz80XUW+U7BPQFO10PNed11QA03rAW6aGEFdcXsmfcmBl07DWLJFXK11Aut+Kk7VXK6DKHdngdtBJI65I3NpW/bv6izAGbJr4KljJZQqhhXhxPHkSSaTk0Vp1wAsYdbSI9so1b/ltJ+hR6j2UIxlsy3/uMwUk6NvP/SkHkTzYQX0AV65gsc3A4zfGM,iv:0DqFvcHEVRccyM+iRRBnvW8dHukG9GdatjtMkxbFzUw=,tag:tPl7UBfWJyholuRpfz/hfQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:dUup41iIH8x973unjXQn8k7v+cWlIXjPvM3BOno8IjpiOfFaFpniRo33fXOGjQZ9QXTwRjKk3ujwBccE9vBirevt1ix/fE3fzcu8tnJSMKWz4P19lAN9682esXHMgBlUqp/VHKc/Mo/2om/eA1h9r20Jc7aElSJijO22CAoAFYQpbhDCYjYYxSD5LMhRggaY5pJjtbQTi6bEcV3ihHibLLZ0IIWcz+fKrnM595ggrOv6HZCdpw9maA5noBF+enKZPbBLBQaWH3S19UleAA==,iv:cFJ9m65hD5CODlfNsjKAT//XlqkH1v1HXZNCPClHX30=,tag:jvZfXVWd/pxJusal6yzluQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:+oW7+brmSS2qsSVftA8067VgSilhL5/8dU82K9+crTDDWTweHcHmPIXc5FcaRtruAHuZ9SENzeh0NzP8PkQ0XIqgwFZl341+JQfmmwptKmZ0C1CJKHLrDHoIQgQTJlJmjPZRya6lLGBsfh6GhY7E1Uw4B/Nook44j8IewsoatPdVwlwILVSCKYps2A23gZ/Mq7b9WMvnqoTII+PK7y/tv2/qiPYeZrM16/uu,iv:eNlOssaHFbrQyiHQv7k4A3AoBaTCmqa6THt23PObu/8=,tag:2Wt5u1xw3S1TetYWm05fUg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1ahhpeqda220h75jh8fwfptlze88sggr70lu3vzzylhj9phtm730sj06q7m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0Lzh0Tm1iRlJQKzdnVFlI
            RndwVGRoTXpEY1Yxd3EvSzFsZllUSVZrL1RnCjZmSG1TUFkvZHdaaU0vNC92dHRY
            cWE0YllwWUdpamNSb0dib3UzSXZsMlkKLS0tIE0wM2hnWlJoOFc1TGppNGh1ZGhD
            eng4cmRqN0JSTDYvQ0FWU3E2UWlaQkkKv6b1BDuUoL2ViFijQo13yr48dqr1UQAW
            Ts8TLl2fR9T8c1CT/pz2K3jpvn8dmlzEmC3X6C0nT/Pbn3N4OaGMMw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-20T18:53:36Z"
    mac: ENC[AES256_GCM,data:AevVquT+vXoS31LjikZNsyfPNKGeSro4Pe0UV0FPDQAXgmDvNhPh3JHut9+IFjwjSX+LR7Jq4mLdMsXsJu1FFEaVhtkgslFk1gQIU3jzGfiaDzykToCfWZEdpooF6xEBq2x/mB1aGCTl0n2D4Fbyn2x11kI/Hqv73qZfIAA73f4=,iv:YQLdiyMDTG6s0pfbxild+AA8vvVLMcmSZ89hhQeRLh0=,tag:VW4UEVLNE+e1GSoLyWa/tA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
