apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:DFGul7kcgUVHwHRbQSM7rdMeCdPR+dpseHOR0tqKoJxXYEYoRSkdbEU9hUekS+gQ5dtStZHLBvwHkrb0iQsoXCgu37xJ84WfX8hG2geDCXoYFvmMQxsJKvqree9mW1mgyvQqZ640cZtN7t0kZ1ZSPJc164YM0BHPQUIVj38mZbhTYYBm+JCSLpm8yd+aZhYG1M2QhdReP4enJQD87D1VaHZKGdZ7FCaAAtGtvWZqZuOG8An40/HcismnMM3pmC9hK/wQBu+4FWo3Lt5tNj+E0uPCOXADkreO2Bhs6nVZKqVmyuF7WGfuhG2du0tnQiOWWE60aiM128bc94PGOD4/96lyOBcBPM9DvfVMXR2QlMfxEqCO06+ZUiX55xIhxoD4,iv:beRYHijI5M3apO/rH5JHh5bUVxiW1ewJOiynOZbLaec=,tag:gCx3leYwMElC/tRg4g0u4A==,type:str]
    identity.pub: ENC[AES256_GCM,data:hA14/BP0t6fOn2R5L7XtgJ3OQA1miWGHnq53i1kS+D3jTnYP9s7YhCtpXMqrHMMYnMnqSUzG53NYK3r5iBYKm98oNWu+FKxS9jaVe+KxhB9cDAbMWQHx7mepm38PleNBDU0Zy+7xXKUeZRizRPY3F3LNf2+pyqMSBZgikhrz82adWrhzPEogmbnH1zVEDJ1Z1nJ5CyCnkp/fK1Vlxt1ZrD6ioaZaKkrDxFCrFj4ruDkg6t1Z2hRmrIJnmnh61uORlRW3Z70Q19Pic7EMaw==,iv:OEcpfHTtPS5xSe40qk/0C1tN2XfiAc6dBOOH2EBXgKo=,tag:RXrAoN+20J+p18PlHsud6Q==,type:str]
    known_hosts: ENC[AES256_GCM,data:zPl6CGjrQx1lsu+nm7N6Jh2whNfin1Hvnxsws3Yu9DjPrPDDO91oSc1T6tTKx3F5EPXT6nq3xHxNzxU1AZqc0ito9E58lEy2vuULNPpkH4SfesgPc9yfvD6NiEzhVzqfTIjzXBFk0Uyj4SNU0qbu47KZqVG2vruG6dbsqLc5oSSZpIk5h4asF+7DZ0t8hIxzpDyaTWOnyJkdB+1VzdC31NolAAOnkj/pMonU,iv:4bkappK0S9uOin1HGPZqPk4q53LyLwZH8rKFle9h6qc=,tag:7/Pl48bKpw7rn5QMan5mrw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1ahhpeqda220h75jh8fwfptlze88sggr70lu3vzzylhj9phtm730sj06q7m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlNHZvK1R4Sm02YVJGSmdi
            UElaRnRmem56ZUNjV1duelBFbExLVUtrTTNNCjlhaVh4NDJFWGxlbTZ2NytKbkJM
            WUREZEF6ZmNXdE45V2swbFp1T2V3UVkKLS0tIGxkcE5waUxBdlBOZTlWZ2hzUU9O
            Wkl2eTQ4YUR2ZEx5dnNCc2JRMkk1dFEKT55uU4uW9+OQFquMZtp7H9Nfiuy0lxAn
            G4hcBPioyhjt5ZZH4tm8ek42YhfFtPatFFBgwE/0YlXr1LYsmproHA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-28T21:59:28Z"
    mac: ENC[AES256_GCM,data:ZmLE14TXqUdBxEkR4zM+aL/22NS67Ys1rW2R4+5X1LJqajJv0+nGB0jLa6Fg06Eqdxlgs2uKs3Tsou7RvhICRB3p8wGFhcwZQ4UFiMG9WHTeVGr3eN8siQLNMRHA9q70WLzV+t6vRHy7FbHhJR0T35ssdrLTfZfzb1S5uU6i66o=,iv:Ri7yKbHAcnSHANamqz930KfLH/l1dQvcA834ipuPGkQ=,tag:9ZLA5obhIEd2WG5vnX5xxQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
