apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:Jl2eSiFyyjAXkdspihyEdyjGkA9FCF6ex/urme0vqXdWKd0gSA1lHITSkqv0Z5Iog+v42tGLyu/ZTgeX8JM9lvymNmT76p3BdL4F4AMDGPhQB4+hLYEnf/gQsR4v8t31xJjgE4QkcBmqy7jkoVvY1Fnn2Md9e10o4sZXuUyeqJJ9kdO5tCJXIUcGcLw5CqvbzF/rdb6cCFOsO/1ayhTEBHCTAdo0xh5dnH5p6fjq48YmMhkWtd0mDtF1PQTPhzNn+zDOkWL675bRIx4jfW4f0nllWsRFrkzNxzXC8WLBB3mLOzR0mQNRPP73VS9j0AnFZjLm89OzH3bwZVM052esgPttThiIvN1BLseGGcvVFrWpw53jPtGZ7AOI/RGJx29E,iv:v+VGh9AnlQAkjdSiQzbtv4Ra4YbxYH8+54G0J4FFv+o=,tag:GFecDE523U4EshbosNHJhw==,type:str]
    identity.pub: ENC[AES256_GCM,data:a50q1NzpMos9WZMl7/YIfsoG1QHSv2yN8QSMvUk+bYCZMAqk2FnovrDaSaZAPRtmHlFgA+tAyMj8mgcyuNpTWHQZSKj5ptx85MtCsnKgD6gkgroFecOzI8+dR05EnYRH4N6pwm5cywH7GbOwzI7ELehDU4FtZ8ShC20O6g2VgG1ZIHIskXSIp8gPB6GnhJcuGKPyxOBAqmcBGvPUIoH3f9juJIkc+31XTSGg2Du1zeJzcmNy+ZxnWS8hYZAEtmdEw1UdqMZVb205cHo4ag==,iv:xJxfyulfsFGv5HK/cIyXR38pQ0kHTKgFFgRUgGa6fO0=,tag:MgOrvM7nMAira6TsPeUD1Q==,type:str]
    known_hosts: ENC[AES256_GCM,data:veWAuYGFw8yiF90k8+cCmLVMlRK0t+GA9v1x+VKcaFXOGYOBL/926Ky/9zdpwJUmBrc7RT6UBSPG6059bKkJ14E3RI2HBmLSVKido9aVFHNrfzOQ6oeTZAv7t7jSYuO4UHiINe3g+3y4t/D0zeOE5RoOSlvUevJg+28Y5Rjl0rNW8f9Qjb7N+h+pSdq+mQrqSYw57AGeSvrCOFy+/mLqAqO0wW8ku/+eWTdz,iv:mkZPhkdG3b1ZoFMrrRheZ6LbwvduyC8nLQitBvz/Xjk=,tag:k7+xw/pANWuDDfEXz1YukA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1ahhpeqda220h75jh8fwfptlze88sggr70lu3vzzylhj9phtm730sj06q7m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUNVA4ZE1CdmxFS3pDdFJj
            Y1g1VmNVRnlkQzlESnVHcHkxMTZSbmozZlhrCjd5RnVZRFhxS2N1QW05ZGFJOXEv
            b2VuWjJ5bi91ZGp2V2tFY3FEU1hqS3cKLS0tIFVDaTVpK3JOUmU0NXNnQW9icVZ1
            RlZDS0FiY2xuN0M1cDJtQ0ZYbzR2ODAK291kQ9nPJFcFaMyOMa0osbz6XqqUMQRi
            triEUJKXrGRTSw50a9nqQUXRipSpLTyJPlltoob3XB9w8jxIywvvAg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-17T16:04:27Z"
    mac: ENC[AES256_GCM,data:9IWI6PVGDiVORvR32iXyJmw9DpYfwvT2oTfA3t7NtXRp5MDlXE/h3+nVTrhUEdpqzo1fCTo7FNINvju33WWGWsj58SyPjW06Az3qu7W5CSVw2MQ33lDYJV2GTDvGnpa6x0CDJLu1vqHGDM/uSh/LP/TqLecfnemR1Bgo0pHGh4o=,iv:viSXHPm/BRxggeuOIyWt6xfkzVUrG9BFeDvQPlopfZs=,tag:jlpr5AcSCYB2ADur/GGeow==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
