apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:iW6pbHcJrMZ0CbVGHbFgBPSYEHbgvXQibk1w7hfbyhJm/CggxFAWIk5ZZQw63wa+l5qTm1PGfcb/PBMvVKE3A8d4JVOoxMVQtZ5Giw95P2zgn9nr+3wAbl3iiZn6xWs3IYfJdfQ4f+eVgXxzzpgjN9cjcXoUEBylSnaYkiRS0BObA0uZyUAuYIuZOLU8wRCEdtyhG1KF4+YYmjmHxHVi0GqrCj3DtMAJdJf2FAfZ6a45gVii9Y/VVWv2ScKUFw+jflffe2fZrHy53qnsDGyzf/DN80xtPlob+BLurOrgPbYOgTh+dhW/Va04ulN/9gUDPO+CJYzRnk4nEPMc0dJwsBEuiZiRt2EJ0ON56zg1nSfnd9RTlcnYEf/la0JinA1M,iv:CZMUJEG1FRYZ+EPWQ9COipe2lI06PaVSoysUW8lFINo=,tag:TzkFY6gNP06LcDHeZgB9jw==,type:str]
    identity.pub: ENC[AES256_GCM,data:pESBSEG5anBoFBh+CoefGFs6lhykVpF78n7aRBSi2KSUeBhPZ3YdlpqCsclkNTDGLxmMU51R59pl/YjR0sBb9OEtRNF/Ky7Rc4LRIRlHK6nE+QWywz0AyAbQo2k+3sStK8jsGD2Qjl0NPjGlygnsLRpXOcr2ORhC25G+eNEPFm/uoRnvxPn3ZgQXrF++gpBMsNW946aykg03dZifHXrkON7V/pII5lxxKM3XlDmz/v18AkkDo8hG816x5/HjY7QCLZZOkSSu8oD8ie8MEw==,iv:4PzzcAVXoyvkv9M68hvJjaZpKKzvR2fm6ATAYOvP4Bk=,tag:Qz3QI38xazrs+dc92JyL6g==,type:str]
    known_hosts: ENC[AES256_GCM,data:5CK+eZxuoyJ8ZzTiKYhuFgA0nA0GkEOZ5F7IZFpSu+fiIEOFhXAEP8OQ8uY/sthkayTZaMtJivhUeaB0F8STSqVlAVLO2cKHOBCzW0lzZHn6CmKoHMKfVbwtX9FlDOW98w+UvIECh6DgmPb395OG0ILc3AyzUxx2SxZ9iDGYfLOcZGwVE4EkQk0+rLM1+KV21u+q1wtrRLUsf5JKrPNbrI1Sw4C6lmWRMU0h,iv:O1Q+0t5i4VBzja+yVCFiD+zpTauHTBYG2RE6gw93zok=,tag:KwzkhnLM4t93zq+Ozt45Ww==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1ahhpeqda220h75jh8fwfptlze88sggr70lu3vzzylhj9phtm730sj06q7m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsOEdwMkcvc1pnMXN3TDN1
            RnpTSkFRU2I0WE5Ya24wK1ZyNDRXeWF1OXg4ClB2TzV3WGNvVkM0cC9ZNzB6WER1
            R0RiZ1U2NlpKMmQrZlhFWlF0RWM5QUEKLS0tIHdwcHJJbGRHRS9HTU5QQ2RYUE0y
            RkhOc21FM3BJV1oyRGU0VE5KcE42eTgK0AJgd3N3ZRaZV/x1EdXQfyBXw7Fz3qeE
            oBO0xxqkAwk53IChdG5h7CeaAcrt+a055WgLtKOMTFPmXuSnaprsYQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-19T00:11:06Z"
    mac: ENC[AES256_GCM,data:5u5pQILXL69iyLk9kvnz5aA3mTBTSNY0lCuG0VcF+D2awpOqbuP8Ic2EYfIWtz61IO3xlw2E52QNd36tK3V49XC/HEwLIGLBAOLMPE1yhgK6NZVCm6nWLYuN6yNIoXuhlz1L6ACHBzaPcQW0AK5M5fzdzmIH1HnfD6L20bccFzA=,iv:fc1GePUbDsoOMqOvSR6itoq3rdRdMSF+49HB574X8qo=,tag:K/b5QxMAJFflfihs/xNuKw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
