apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:QWIv0AYHY3YXYNO3OiKWjX8aLEQFnR0pU/Ly4xvxe7kRIfnBFTfE23JcL4GlbSxicsa7pMpq4lORF9TagoDzNLHWiE2qbn3nySriP7Ds4QJXF38H3oxMMS8krn7mrCg33yB07w1OmAeJVbLcqwl38v6Q5Xj7cEqBvgRzlJS5A0APDNhQU3as1gYRJrDv9Mb8mpo9qPZAzqsesMo5uu3FZpWQS0xPz5dEgiy7OjVsJ+hAqkivQPwWlb7OuQ/UOOW+ekYwnm/aQNfItjF7MYT9Ip3GAEIioEx8BWVRSXRQz0rdQdvtUI2DoNRPZ8jU0xcSs0S44PWa/W3NAp7A7tJL2CUWvxDSp04ZAPA92r94us7VvwvslSxj5zbNETkvMP7x,iv:qDv6dOHVg9BbtjgZKhSXqpJckmwrb021Sg0cnVCpq5k=,tag:yj3YngeWo61JmKCKoLNCbQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:VHeL8fMirlK9l4wzbuTyAq2s6gwPxuNFesvdlutbfZGkDSUWOHR6O86B4aggSABEyTKgZ9mbVHUCyN/BfBn4lI3f71NQCaBCYJe/RRaIX9swjGlb3Mdl0eRj+nVBehX+sfouRYy4j6AxZz5Je/pUy0IbhpMn9/Y5myA9zI0/UgACcNaxamYv44zCDkgWLxMzx8ztslKyODFmsfjd05tKmXbuiziHMB3h+gT0Q149nWaaQZhc2F+Ri0HAHAWtVhyXgHbssGnoyGVvdTOdGg==,iv:HwILFcwTD6pqVsVGX9/Muk6YnYcbhr0M/aa8ey/WeGE=,tag:Tgqf1qg2WCx/AK++SbbzuA==,type:str]
    known_hosts: ENC[AES256_GCM,data:xLgup1zCR4CKzopyXvjqKjmNRybzGoZHOFgv50Xcj3h7FEaZfzJAZcpGzIVnln4Bqvjm5CUHUpqjNLPdTbaxAaIOar7LFKEKmZDieTG8UcJ1J99B8BHF2N9UWXFoGmXvLUOZRiLhBMucQE9AIE7KUNBKVEVga0A7uSpez4sUT/QRpgdzZ6XKkZ2GqJVe1RW8gUmCUtgUwXFkXk/BY9vZARP6Lv5yoMSexbEs,iv:V2/ORYXJ03S6++6WnfJbHomolAZ0E2S8bmF0V+g2AkQ=,tag:EVQd0YYxXvjhqToYBPWTVg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1ahhpeqda220h75jh8fwfptlze88sggr70lu3vzzylhj9phtm730sj06q7m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYTlJ2ckZxeU9Iam5TbFJ5
            ZlE3VGxicXRMeWwxWEN5TFNMRyt4anhjRFR3ClNwWENlZlFBVnYxcXg0cmg3blIx
            YkpSdWkzQjZSSkhoMmVBdEpUUlZCaUEKLS0tIFpBZXpxaExBZjJ4OHJWQkQ0L1JU
            WW5XcEVPMS91bm1jRlFqR1MvZGpQUEEKV0cM4M/PAgOxwZTg4BxcRn83icJMiVcL
            ASIfkZU4aGVslpDyHsFKzpRq+A6IVrMMmWnOmgUZ5UU6xi50huAPmw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-18T23:54:01Z"
    mac: ENC[AES256_GCM,data:py0ytwhVBRnN8inw5HS9Je2+51mdSG3v743DTliME3SSC2rFhhIuCTKYTt55uAl0OV08QJ4hq9ikNgHF8kj9BibKXNwx4pXGWIM4pcXiXNxIyue72Rdi4MPvCRmjgIEwq9YIz7NdalwRdnqsmTi0qmeopW/yULM0DTonSGPqxHY=,iv:+5nO2FVRodORT0iArbfmM3DXOQXeF++Phq1tQAIxB/Q=,tag:1yT3Sib+3Eupfafr4Faiew==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
