apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:OyH7FJxR/EPWFG3XZeQdSBAuJJrJpSdCkm/X7Fxjfyf+SwK4Lt8IaI9QzFCFbCiWa5vCxAOyHp2Ti8SqexL2WaGFsMhfq2NPnP3GrkMoYaJNdyVuv8Ixwl/MuBuPuGBuqExQDOyRvMqy0MkwHmQc97XbplujfQGt8p5nC4WIxDfgf0fElGzW1Bg+3QF35JkFRgLJvuKjtkCb//4dx0WwIv1Y+xERPQlJQ6OZbS4I32VHB+yOni54QouTB3dDSvAXp9sWJzwf/MiiOa3Y5fiyufrGKWoWuw0DVeifm8a/DrfemIyWSvz8BEjrnYC1bUGORzUbQd+DChzwwegP5MfO3f0+JYRxnfI29vLIG3aRkW2CH1NwKh76xFic0WnyyLxL,iv:fyVach6ej4mE8zOmn4WDRYHIYStrqmKeIaZuSWg/bzs=,tag:IoftoIGFuRQvFkET7MSYHw==,type:str]
    identity.pub: ENC[AES256_GCM,data:SEX/WHiyKB0NPuenfYL7pPkvnHx7E10bD1dxruCCBWEj7So+C9mlhn88rDDliD0/AvVkD0TzfTANZceT3knbQZ+SRL407Nwvy2cPo8ijx7LStyzjQGLfi2ZhTX1MSgVKU5KKXpbJpVnVS9SWauBYogfzixOjjFpnvkmigZAN9WqoCepoSfhJIXl6svDt3cancMgV5KyA6Dwjd5wmNQHa85Q4Mf5yQRaWqfOjdefbsstPKfGJQspDNokYsYR490MFQMusmKVf6cT4Y/qNKA==,iv:BkNtXzMldvE2gB0ZS2bFuemUxwX2YbbcxjgwqhRhEdk=,tag:PWB1oxtd/4yWaooWtYZsLQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:u9gEi3ljrzlieDBq8gvP83na+JU41/6ipr2/fYgqr/vkA3a6YlS8i27/PKlYJGsx2kFZ1TXHHUkxFlZMrzRMLzc0L/tlu5BOlikJY33SB8yyLSDJkAdkhJ2mtMaz6oXHFZXu1MY7dbc9FWErzxT8cqCmA5GgUJv4aOgPXJaAG5IlT3R3Gh4hHGpa8IWJpub+aN8DoJOvh6UwhzaNDVFmZHFADzqR/JlTOnVL,iv:c1l8MRTmEJGuQQzNGV1kdpg8bPYhmBgzBH5Rk3kOZMQ=,tag:sYF/WkoJSmnAzKqnpkgmjA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1ahhpeqda220h75jh8fwfptlze88sggr70lu3vzzylhj9phtm730sj06q7m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlMzh4TnVwelZpWWFMcFNB
            Nzc0aStWRFNleDFtRklwY0RrTXFaMFdFVENJCi9vYUlIRVNrKzNlS0toNmpDZkJ1
            ek1SRmRSWi9sbDRZSEZyMkxRdSswRG8KLS0tIDlxLytoUS9WOERTejVWL1hRR1dX
            M08yUmpkUmhEY3lLZnBzUjZtcmZCWGcKxL8v3/zYEAGF0bWokFZfz8XR1j9nWjct
            2G8lcZVlSNBdGD0w1TBo+GByKsji0wA0i63aNCuXfUHSO9llghbR+w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-18T22:38:34Z"
    mac: ENC[AES256_GCM,data:gkUYcJb/tj7HAEPbuyh4dL7Rw6j5JL2XiOXFf0f21gUQsRb49eXOB8OuAkJV4t2LI110JdmlbWEJowFa8JUuYS/FXGOeE68RrXOC/L6M+E2dFm9PhdTVwNb6pQ9qpjG/RZyWQusDaH/QN1+NParKYbsGKp71YEdcyjYc/lZNov0=,iv:Gw/oPpszuhBZG7dAEywDrBS5xNXNQ3ksscgO4xe4Tn0=,tag:FmjP40sC4tIUiXnq9IcZBg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
