apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:VlWBDTzzq3nQ2j4wU4v4GYo7wOfVTFyobKCbgwmVH6P+kdcmIeWuJcxI4vihCiV1tjuu1nXhwPQ6SjakgNkwwTZrzhYTIsdwYi2CQO0MopqiLLx2DxJt1UblrxLfvOJ5+gN5Zz/ljC90f92HVzJ8NV7PexPh+KVARCPtyebcnVJ9uP9I8zUH5RmPu7vBWEPgDms8kIUNXdBh3G1AEread1usAMBiCABPsngi558/YkIyIO6fZ0aNvEtP7YA4j7+qSH3ut6WQ4LBsg/fBjDykBRsCyJuV1q5g/xsNWf1Rd/tgbC2X+aTuyx1QAcaknGH9Nz0Fo8ZW0faAacLmnplu35he+mBf/OADwD1nWcJhksmk29ZG3gIBxxRM8YVefi28,iv:WThxl8xb0gbFPYwuKv7O89ZXvncHO/rib3SnPG/NbrA=,tag:7Lc1r2VsCzKeU3seXX8iDw==,type:str]
    identity.pub: ENC[AES256_GCM,data:wVlke59p2GNLQaRRyHLHdeQzTIJZnJV9MMaZUuO+mekzYq0jcjbBSPj5JaqOMJ3uCFycw2RmvKnKpeWweWrvw+D2ZlIAMz5S6buF35EpWtLtgIzPz9Odc6UpZo7q3X6bUgcljAalG0EJVwJzyAbUlj0Zi6MrJJMesL5FoRwtlZEHlUDVMNthXZutDPZgjH4cy+yKkzvAsDdNC6McfXup3dhOqdex+8YfwEWx+phin+jkbPWhypv0jC/8zC0054iV1uHV5IHk77cNTfVKCQ==,iv:XJdvU7dGgHyiPlaADdU3e8YjSLWv9pf3m2mwbcfLKcI=,tag:+ET8/E4Am0NP80JS0kl0rA==,type:str]
    known_hosts: ENC[AES256_GCM,data:55W5akYHV0VO8yxKzy/szdgwa19sadiBSqp2/I3vwFwPwF3+J4sVcZwczG3fvAc4h3o8ZgLtjID1qIhYs/9lkoGq3NQypQfZ6dXkgP4+TEVHfccC+KN12TxYkOgznb/m7HeaTex+QMhXiNVrXF0y4MJdkdm7YU9DqBAfJTQql0f0xz6/L4bZ4G0tNSnULhhnZ69+WGIC5OcF2VesCupdkVuqVjHQeSKyoKzz,iv:Lw0MgiPgoYOn720yEnRZNGomdPF5SfpgT/0QoOa4alU=,tag:S3G0zWb2nNCMZEBNCddLTw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1ahhpeqda220h75jh8fwfptlze88sggr70lu3vzzylhj9phtm730sj06q7m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1ZU90ZVE0TXpENGNyRzdS
            UjR3akJSQXR3aEtXWXczRnozcW93RXpwZGxvCkhSd08zSXFNY0hwK2VMYldFNmxG
            TEEyUk5HZmhjRlptam43UEg3WnA2S0EKLS0tIHR3dk95aXpaN0FBcDMrSEQ1Ti9S
            RG5Od0NGTnFyKzdvNXNWY2xLcEN2TEUKu9C0OMslEMsPCnc1s5G38R/qaixKAqLd
            b+ZNJ6+2AJLihAO6i2kefF9lABBnU8y7uwEusKiKgNqciwj26VD/mg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-28T22:11:56Z"
    mac: ENC[AES256_GCM,data:2Wdj0Pt7WALG4h65XI+Rrvlxwu1Lo5M105KWIVGFU+/59yXGin82GvS3JXZ0H2HmXn89rP8Ze1LGILnU12ixRKecQe4qcvsCpVNsSFDdLzWNfDl5FLBIo97eHFrzB7Io2cEmQu0L8JsNbNW48ZA0es/8hJtVREFkEtGdisbyEtw=,iv:EEKZeUdAeIjIE82OIgACNuoh9CcuNZubxzkOLGJHvWI=,tag:vwGwmQMQiv6dF6ChhNWYgA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
