apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:ip4jO/aRs9j0dHeC85/jznN7mYS8or7Pj4PIsdqlFTp/57U5eaBV/PzMWvs8tCIE/kJcW5WsIcoUBnEk+lHkRn57x17YD7H2jzM2a7qFRp5+6t2Mc4+Oyi22uwvdrMO4yaqJ6/9fBuJKjHT0b+KzzkS9wTOzttpEIHZQkPxDk20NvNAukW75JvbL9YSz6UynpfZQ+kRAYUzg7/VsgIYI3Pnnemzhyyq5fNY9qVrOnHglwqTLaJEFEQA7dkObw+LigBpiFqL0BmU9ECX8+QZ7Ar4MPLLHISuBrFmgl3w+taQqTjr4vQBgpSRIiO/Aaf+5JiNOxpNQV3qsCKPp8QXqErkETpBq0unqCkw5fdFwzCzVvWcqn8BDD9vtwhv6/W9q,iv:58raVYJErqa8XQB8dmP1KApv4aB3QvGnk2J+MY2aS7c=,tag:PIe6XgKzq7GWz46tgmewIw==,type:str]
    identity.pub: ENC[AES256_GCM,data:O5BMshPivDb4TDgizwuUwbIfu9lUXvi8pONGtN1M/wFHYWO82B3WM9TgzWppuV/WjzS0mT5UwEo1w05QQLBXttcyCmhPjU3N+iJTO7i2mjoPgfFKH3ttu4V4hQNt0ccRNbZzGW0n/lvt0oLn+NuLHyMq9ZxvJny8y34wtCsQw2euUx531MH4UGvI4TbKzf2Msx3eurTrlY7J1c5eRZFZwah0eqegZmFcY6foq/oxCDFLdGvEZitqG7KkO1BFf5+VgjtFglt8nFPC4HN4Dg==,iv:ZYOq3KkbObxKKhC65f2w+TE+rJg0TKohlpD8iQYQtYA=,tag:v7pVByv7YmCmTuJGQ7OnYQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:FSbesPSSSUMaJzGc9cZ9Bbl1idhqniFAFAvXnGVQbNqhspGm2gBcutuKhel0mRcUrc3gGX+5t23gW9QBT43HKCf2pyp9rgd6m8TDA2CYjQRyLHDYR5LmRqYE7Up9100ICDmfumsqVgd+aQHGhyTvKWNh9cX1Og+cK/hrcxEf3POSbf7j/1idW4G7yzIZ4R/gYd/v7KxPQEDUZlT7zuvznQnFjxkCDOYCGpfV,iv:ifjVOB2+nAdFuHV7B688yfAVtH+HJUqed/ovYL9RaRM=,tag:FWHBhtg+BJ7nofD4F1HB1A==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1ahhpeqda220h75jh8fwfptlze88sggr70lu3vzzylhj9phtm730sj06q7m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxQUtuVFFTL2xLSUdsT0RQ
            SU5jZkpRMHNhMHM5b1VpNzdWR2huaXFPV1hZCnRRV3F0eTJtelZZaUpzMHZaYmdx
            dlYvVW5jbkR3WG9IWUJPQWxlOVUxZUEKLS0tIHhaWUwyWmpsQXdHK0t3MTJIcFB4
            KzEzbTJuY2pvT1RHVnN3SmFQc3NnckEK09y9FBMqh41vHa0GP7dDZZh5Gsm8mErq
            kG+e0p1OzkJzS3FNwFn27fIFLgFPHfadRDqv52Lt6+E+cSaEFBD2oQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-17T20:49:41Z"
    mac: ENC[AES256_GCM,data:YzoHTu9OgPmPiu4U+6Aby/hJv+OJvV8qkFbQHejiNIL5zPAjEKDE1ikbJ7HiPfm6jwnR4aVXqPred5PfV3+y/sRMcoWgl5zk87sjtSdsGsVgT+51VmN8j8RFXFXGjzyOIOJutAcxRCv+xt4yb9/UWpsEyJS5QzFH7n8E2YL7OE4=,iv:qWSg3/tdxIXSzG0v4Yb9LJSa9VQuxbXWKOzkMTwrWYY=,tag:7bzpgtt39f7xr7fQX5dYrg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
