apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:emtLG7PZPMKc4a5IPY0UYQCMlVy5bFxh8TK6FrImIuPPEkd0GqYeRNUJ6hMFqnwKPRAliyKxB3H1ozoe0QbEhLwn2ZsDuQmMD6humS61jzYM+4lN9itPNQsEWl7F9hln6Ah0Zv0Go2bYIokIK7yF7OolRAWt0BrQ24hpTuapZN4obXxl10phw6BTDIcXl41k4/ZB8+je7znt4TXHN/cbo2K3vDiGJGCpu9XyvRIlHCXzNBEVXDZazpsGBzdmQTwlBbfqN2KIRplJ57rgaiWTzCra53UaBtHt9P5rRtDnPFUh+KxN/1yv6csthiBp/jaU6AaLd2PDKBvuNtwMqDyiLwO8Di7K2vyRP09k1uTwKfDL4gdz+5cNSqUTX+5bUilH,iv:tq7h+Zqiy0X+TfxwdFowt0lJxcVUB9kDbdmJKcGYMFw=,tag:bywy3vyBPtqk1z65LWncYA==,type:str]
    identity.pub: ENC[AES256_GCM,data:7GV1u7/CtTWdumPSOOET6Asl8BmzrAiZQLVyuLLONFdkp2Or1dj9lc2G9XmaYDKigF5chte2xJ2E2VnCKaN77vDkG2N1bkROzgjkahqhHu91t5K8MpxryNALyQKc0fau1KUDTudbTAxgyQQhL3NcBpIoRwqsT3Myo6ZeaKr2LHjwdbHcEDuBb8Pup+iP1qgMNiEroVVm85KvN70fqEel9siUTpuutYsbahy3dg6braTls+++a/DakieP4iewUruJ35qp5aYh7cJKsXgaiw==,iv:K01NwWn7h2QZ/XRf00i3hORzge39j9YxJgBJeXDRdTQ=,tag:gEz+d1o9PQSMPf3B55RzXQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:TlWY7kR9Uqn9Grpu3ypjgATmsDJ0E/U63h2+xXdAL81AAj5osvirt8OoiA9L72VCGo9jx596dYxYTX05bpMgv5C4qLnOag64D674cQSqfeoIuzIT0ZfGoVzi/UZHN7aeDOOyviIJLV5fD8ryypXSAT4LQJxGJczOHwVSAKHgqNTEVF/3sqUbWobJITtj6XLPqsBvywMvL2qtYrHJgpXSEYm7yGPZO9qtv/ll,iv:kWE4Hc1m/alwwEEMNf3h8L66rhd8Gqu72OEhT1QkS3k=,tag:214ymQ7uBfb6rmaTIzV0Xg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1ahhpeqda220h75jh8fwfptlze88sggr70lu3vzzylhj9phtm730sj06q7m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxRGVMQVlhQUN0ZVp2QnR3
            N2Q3MG1wbks3S0tPVk9RSWJYQ1RFL2NNeVhvCjRBVklFM2hBWldDTVd2bmZrNEhp
            bVIzOGRrTEhqUWdHMThQZlZpWHZEdDQKLS0tIEd5T3QwbXRQNEFVeUwyNzdRZFh3
            Qk81OHlMNWJFa0pQM0E5QzlNWEJWVzAKTuhTxprzjGtzmQPYjd7Q0zmbe2sHoPQT
            W40mxSQi34Pgd83dJ6JOlxHLkNO66zlwFbah4mBhfgFYLxdngqIupA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-28T22:05:18Z"
    mac: ENC[AES256_GCM,data:OAF1rhVx7G3myxAK+aYCe2dcuuicOH9FUboZ/pLldi4rOT1FdHszNSApZd9kQCIEOr3VbpsgnI2EVFHx2rzAA7Kg4ZB4Au/Rucja4YjMT5/eRO2WMrf0IcTsQ5iAMof+Td6SHFIJijINShgPwbC5ue7soU18RjTA92udL6QHUKo=,iv:XzNPCfvFzkY3w+SXWUbUor3BSV4Um2NrBow/CIy6KP8=,tag:5C64/IaRod4dvJIbAv4adQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
