apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:j6mxbUugBfoXD6vnRhEz7i1ryZGWm5n4JQ94IZFy81FbEd5PlYo4luQ6w0MA+ijdO0qk/yok/YPhaRhRhDQ82mFOP5ZwroDhEHOwOS1M/LwZMWJdgNpT6HlUADEY6JJ1uTaW6ZH2/wMn+O7OyGMyHo3rK+T/s6wGJltQWZW489isCZIWSF2ZZ2TVm2K6ZaLo5k+DyIx8lBq9OO8TyKzdrtaf8N+8DpiCQiE0Nhgypu/1wdHf7zl2WcFfT0l0WrbN7w9LPojGwEeoWF7va72/gOg68/lornuCxMPkImpN+o59wcgwEQTrF9L+aba0Le15QGFEj0kGS/PdVGzn+Pf4UqNAk52gCjil1JQfsUg3KK1tYEOFMJM0yYKhSUSeioc7,iv:JhweRG5mV0m+wtbQpsfBGNGzP8dr5kLzYAQQG/TqRKA=,tag:0JjdQbVdOn8d4VYvh9ANng==,type:str]
    identity.pub: ENC[AES256_GCM,data:h7SYB6yZ+X+MezB2BRSf87k5DyHw68HyNMwB592hrRpWgfk6SCj12GmfpDfFw80pMI5OGNIltNe+yn2fzeF0zetDAdJCuOYk8Jeys2tzAj2JqnHwB+Pvp1U51f/JeU3OI2snhv3hlEkjbMjKF/dun6Khp5VsFgj4UyAPExSK0WlF57bAsoTfBbKjAhs8MqSH9ulLsqJLgteT3o/7y1oNYBfihdD6CzLoHx2/P+IJU4vIU+WwfXGkxyHqULb0pwc1wZ+4sSnLmcoQVn+73Q==,iv:yqe43Pb+QK9+TQGqtf3V8XBgOEPYvsPCHNripNRjsZA=,tag:vOIYvqPSxhN6gKpNNdy66g==,type:str]
    known_hosts: ENC[AES256_GCM,data:tjJQCdo4ni/le7w+mhY9BddMwccdjW2IuFRsmxM21tEvjtbVOoHOEaAjNnjtoufze5rBTV6qWZWLWpWJbDWOoSEL2hSGQhQxHt+Sku+BBqWVJgbfOW5NT4m2z5kDqfd91/2m+Sr1oXC9G19MbbxeAHqol3TkgFsvX4ACvBNMjaN4QW/aTJx3uSljgzHpreFl5fhyYxP7ckMIo8ttyOjd9SGAEacOjcQ+Y8b5,iv:07t3PaTYOuRC49GLmtSlfgZo1ljXpuic7WZaB0tSIXM=,tag:ekqObvzPqO1PMO0cjrEzlw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1ahhpeqda220h75jh8fwfptlze88sggr70lu3vzzylhj9phtm730sj06q7m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1aE4wQXNqNW5HMy81eTNW
            dVB0Y2EwSWNtYkp2UGl0Sy84Q0FZeFNCNVNFCi8zTzQ0L3VYQ0NHaXA4M1ByR1oz
            R1JybGFkZ0dSSEdtdG8raTRRWjFOL00KLS0tIDJDQ1pHR1ZwMUt5ZU1zTVIvaTk1
            UGxZTGdTdkJIY3h5dWdxT3Rlb3k5V0kK9IaNmNoxsCn9UMDEv/9NuXyCr0LNVYht
            Gstm+vrSCzScwGT3Ele09OnRfDvPkz4b3QNxZ3KRlllu7HA3GFZCGQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-24T02:49:01Z"
    mac: ENC[AES256_GCM,data:ZCzbVW35cO2kdaQYEL3F5TXTwWv60KZIVvME7XdTToJh46/hPd8QoBWDWT0GufphHlsSKzUNEzHL2B5gSJgyfF9caYZExUnfPkbsXheP2vzMUU7Wx12AvacTFOzARq0W3HK2k/NrYku9QFtc5f+Y7bwaRFb10UH2P9SJlqAdNMA=,iv:8HuAiyw+WjQaCLaEdsSPmKODZ3n7zXT8pslhPfjojp0=,tag:0wDv4WvNv7r5sxFIXEG7hQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
