apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:elKvuBhgGUu73ro6iVsHDdgv22t8VNo16wAZZsEczU02MpB/qqdx0Vb4EsL/gWnpKuPaJ90iYrk+CFexjIpeBzCP82vHD6Mwb3EAT1RTZ6YdXDuBuWFsEXbRrej58T9zptqOwmfFC1+yjbcelEuLq//saE1aAZ5RnsIm/+CyID5/IX6BbyLCjpYzeZA1qlN/50jZzly0XW/geZwwKfq9g1fb1TyWGB/3MTzuaC0GUatD4nP5Q2056kVXyO7LR36XTXk3ye5zIRYmt8dfvgHLiUnrd6dSiFVxnVfsR5om7KxFGvKFNEdoBzFAsmVN1A4TBJQ9AN2mJSwUuN44YoiAV2ETEmEOqo9j5RDgrBrpUBKODxvGgl8H3KFUhUS0rTWz,iv:GTSxxHrXDM1MoUsvwEZDyNRugoxOgWAo+6K+TXVjZyU=,tag:Lf0kGoC9pG3cGtQeHJiqPQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:QbJCeftT2Nxr5fN3tKWxUHsunIRLx1Gkp3LyYdBnUO+awgcL1kupYZ9hPYkuR/OKNTjIaQdzqKKi+L4+GNQnEfLVCjkk4jpm6+Pm8H6VPhlHSTaiQzjgO4dx5zcdP81dAEQqsgpM8KJIyPQlaKHHTwcvuGkiKYl6z/iCaDF7gGipI13IWFYqnU57VIkG6xGV1tGtGcP0kFPeDopc7HTv8SDkfrzRwpaaGw8imBeEy+jqtKX0SQSIrjDhRhhaXU/bECWtQOyEAEWlvOnupg==,iv:jbU0X4w6ma0N9J86e/enP5mtOfBoBg2yO6XmK9bfJSA=,tag:j8IT03P1FdMHfMDj3sNMXA==,type:str]
    known_hosts: ENC[AES256_GCM,data:3v/hOmnbmR7FjP0GL1uQ4TTZHi2sgYeRhL8Faui9W1Cb0HNWXFlS0UhPWfK44FpqmakCamH6btsf83YlwwsYmov07/6YQDcvFTqrW92w7bFWUAvfdRAUQjHwdoZWNDi73Qn8kJkpg8iE0y0A07YWQkua21+irFHtwBsXY3+5fh6gGOZcKal2alhfnt8fr7lHJxeyzvjzdFxtinj5J5xmMJl88UV6N0/G2d2+,iv:13PBSX0kZWBQTqTwG9N8moHTlosvp8SwYxqkgA5OmIE=,tag:soZC9HsoM8vVTvJWpVTfiQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1ahhpeqda220h75jh8fwfptlze88sggr70lu3vzzylhj9phtm730sj06q7m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3dkhoTHIrVHNIL1l5a01J
            RUpiNHgxcjRhNUt3Mndmbk42ZC9Jc2g2Mng4CjBVMTVKS1A4em1PUTVrc1A3T200
            SUVPakNaSzU0REJNS2JSM0x5OTZ2VDQKLS0tIDluaEpWQnV6N2JRZWhjVUEvb0NT
            YTVuVTJTaFpSZlUwODdmaERWcU1URlEKhNKFCWtI0m1s1MpN8lMjmPODbK5k56cf
            2Bo00lrGYisvVHmzvja5znX0M+kQRjCd0hN62f2ny6cjF+KoG1hBTA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-09T01:08:26Z"
    mac: ENC[AES256_GCM,data:VXUIuFvozelPLStkIc/g4Ma96Rloe7UtR+dDF1H/4EdmZ4fktfJJ412MOWUF17xUGmtWhZmvhL5HfTA2C4bawf4EVsOhAecsg7FgzuaYdvjxfC4Day1EE6D8bPyiMgU/4tigUUR68gYp4LV4tIOQa3MPHm3sd1knZH2h140r3Ro=,iv:sno9uLTdklZ5dugbaeCO/t73CFxMpFs7qRNckozVNK8=,tag:Un/QbW+0k2z4x8HYfqm4tQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
