apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:JMg/4M5pjOm3tMtwe1hcEq+cbHkHr9YzHszOXEqAc+KTVs+CgcApPV487NO+jZiKNzDiWdlt2gKqshEffzTun8sH7/D+BUqTfqc/Xv1lNxUqf4WNtaB9JGRuHVIDT3Sv0MktxslTu80lNiPcFt5W1SXqc9pwsj7zUfpJc05zuJO51KNM1ILAKY2Ur9gQKl9Sti7Q81L3TRw0dy++R85Vbwn+/edScGrqgtj8kk90H0UXVDPGUJh4FrCQfAZD3/c+vm2C+25BfmYZnWitnCMkukKt4PTtt6xqSXkD6KMB/aHdvanErR5JlUdBmqhap6RvbYYLnaAo08xZAJX2ypTf3ukuPGWb2SPS4w7GxFUko6wrLRopqMyXcw2QCWOGlC3A,iv:oO83RSP5WP9FHhQLNlPL3d98N26w5NxXP65un7588vo=,tag:Jsxp4pSQ1QLWPQLFBc1+Dg==,type:str]
    identity.pub: ENC[AES256_GCM,data:G1tw0QwJjm3eFN1d9nZJlfqbu113cVbWqRrlUN0NNat5DdOuVpy/W+bKDH9gXJ2DrQfmpieKWzfu5Rvx9Ih9xb1XGnGCj21fso9zSgGXQ2hrjO+glsN+PZQreZVe8f0RBwEgu+wt6dBrCqED6FyHUAvzQvS+YD+D+8fUcmq7sVlFkCkhkISZ5a6HnOWu6LXIcPe0eMjdIAG4D+ovWHN/R/Zqt1jNZlKk7LQFXX/W2ioYcx9toIMxxzyaW3J5ULz7dj6UGuE6/biuoFNaCg==,iv:doJVDlx9WUch1c2nA5b8iorzeZLJDiO2jGaJk+gri9k=,tag:2a+yoqI3ZAJaXjPvLm0n7A==,type:str]
    known_hosts: ENC[AES256_GCM,data:zyaTC+S6qnd81CRF/7fEqBU4ofwb/WMsuKzwrxx0j/52kjm1gIig6ofvwEqMfZM1ubw5Mt9A/P0wdQ7aP+ucK0KxHpcGNH04xW9VrIB9iYCGo3VG6LyeWWlT2Bg7hfL4VSOa5uStVaTGY5kmG8ceGmWkWu/ePqAyot2Z7GX1DVuiCO4VFwSx55/WZJiX6aWwP6GKCKvSZxOY3Lojhc5cc2mgwCxLEGDnmku5,iv:vl93rEKlTzy7Ep7G2jklYC2XzKe0Xwoz6fWbSvGysV4=,tag:5iHOVYSBW9CYl3afmHD5/A==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1ahhpeqda220h75jh8fwfptlze88sggr70lu3vzzylhj9phtm730sj06q7m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPL1plSnE0MUN1M0pia29P
            M1F5KzNWWnl0K01ZUU1tZzVPenVWM0YyNDBNCjFxdUkxdUluNW9uQlNBaWgweWl6
            aXpISHRSeTFGRW5yNXNjUW5KeTZTRGcKLS0tIFlYYnFCS3A4V3JJWmh5L2hPM3Ft
            RlR2NjF5T0haZjVYeElGd2lJd040RW8Ko86W5SwlF/hvaeFP0haossDDRUIGi8SR
            FzZ8K9IBDDTRc4r8VOSPS+Mg4XddSaqtu0islstt9Ul0piu6PFVpLw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-09T03:53:22Z"
    mac: ENC[AES256_GCM,data:9FAFKp6SwMbNVOM5n9UzflZy5PMddZ1aVrRerpBadwgIx9hOdL9UgkC8dfh6i8QIegWPsZJrvgdnCr0hYKag2YUoxW9z/ITxdE5vbugP+cUqbj+UP/rP0HKnaegtuIVa3/i3Usz5b9LAFoJG0NgHIM3oa1/QVwkAqWkQ4bXomss=,iv:dFz4271WuEaxGSWr22nx9lPKUY6D9Wqd2YoMVDidNEg=,tag:ZE65ITsGWiMcXJsumB2eTQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
