apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:8b8cbNrLuXcTJHOyzGzQlaepnnU4JPLabrmvr0W6GvPYgSI3HZzZTAU6brgkDQB4H4LB3wdZ+u7JLqMJX1OMH89mx4fB8WKdnEcvUeKUmX78/p1dc9AIE2a4L3pTKVInKquhEw0ZWft/5zvNI2TmMgLm5GLG5w+D01fuLY6rZxET4l26ouMIM6X6TbUL5RNoZI+HZbkXb1pVUjNNeDO3aSpCpvi4qODp8Hk2a/nnED/QzjCkQa2DiTol2vUWeGNj1aJ6DiWfxMDNKAQnWXqUR+D7gDeR0OpDemQe+Q5MjkZUbRdqTsMrCVh4C1wyEe0sPXEaZCYckHB4ncjfU7mmpiY4oZzshvwqmYEjG0GegHqutBFeKCisnpyO2/C/0YBq,iv:Sf0ItW0P2rGO+UBFgJwSgf6c1tTDGDOBudbrvES+88U=,tag:njf5voyda2KFel8iFdVqYQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:JBl9fGJC8nkj0xRwdmly0pA1GOLw3CeWmUL8F06nXr4QFZSvq34r2NdobCcTSlz+CYl1kC9Pkd3C2mjjdJrtyDQ+e4oQ1bGVynxux7wdl0ucZRy1nvP1s5I4UN/HshoVGXoxrRSuTa9lHpUCMbZ/V0QhBvGJ614hqU8BewZp+BFdxidnQ5cY4MIMI8i6GTNJ8/+KHHjkZB/gKmZz6OKVRcmoX/vy/uKWb3GHBt717sNjv0IAHVUdNXehwyzIg2SbdJsZ7UM72ELIZOaOlQ==,iv:WwBuoE5Ydb/K6zGbuFMlQxYmcdfYAT6HiKa51tW0qKY=,tag:ucc7z6qjb/jYCIf1XWY1pw==,type:str]
    known_hosts: ENC[AES256_GCM,data:pV1Q/ZrDz4+I29Ar3dUXGhI3SpvG7GDZnd7un2wYV22v2FSJE/2z+Q9zIWdkzUZgrABpJByb4k72fS2WYdsNcegfnseDLUP6JLUp5osrfDydOfyDEhOqjH6i/QuF/yIIX9T+SJ/jzCAusN381J7MZP0WeSudcjoqlWKIzKfwU1ie9ppysHsfVebX9+J9INtHcNpavkv8iQFjRIW3PlH6x9AXcENUAZhSa7Fx,iv:fIHAkw3mmDvQjGruvzR0AeZjuBBJQU1CFezbIOBnVr4=,tag:q9JN8m7Ei3q1oOgyxAGB8w==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1ahhpeqda220h75jh8fwfptlze88sggr70lu3vzzylhj9phtm730sj06q7m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBja292K2h5dUFKVUl0bUNB
            NlZ5eXJpY1FSUzl4VUJsMmcxS0xaSGZjY1hBCmVycVplWXdxS0p5QitETUFXWkxS
            dW9JTndFNGN1U1kweTZxT2xBa2F1WHcKLS0tIHlaMWhJTWlTR2FsOG9KOUR2dDcx
            emYwVjBHWnQ1eVJwSGlXVHdESlF5MDAK0MHbB/kqXgFo3saxB+YJm2IIngR16JI0
            sJFh4qrleKmJtbuAprPBSOo38zZb3Wa3DTnyKJSFS3VDZepyFBCj+Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-27T17:14:39Z"
    mac: ENC[AES256_GCM,data:sAPPckJDVsZk1cHlQUOgd0yx+FWAFnH5lyPg+TsrIMq+TLbFqf9nmFxDgarJ9mVflLyp4XQftq+CiLU7WJ9UQwinO2kfrgb6V1f57Zi71cjGC+gvMkRNcGgfTgGMEtmg3+/Jy2+FHRdQdytUUKMoA4nhCR93Pi1NPAfga8Y1V4w=,iv:HkCrRK3Tz9zoSkmQuKFXwlW7kX7eUEq8I4pIoOvuWK8=,tag:UsKW5BHKzA4GNyiLoAFk2Q==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
