apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ext-trueconf
  namespace: flux-system
spec:
  interval: 10m
  path: clusters/main/kubernetes/apps/ext-trueconf/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster

