apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: rocket-life-dev
  namespace: flux-system
spec:
  interval: 10m
  path: clusters/main/kubernetes/apps/rocket-life-dev/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster

